apiVersion: 1

datasources:
  - name: Beyvra Prometheus
    uid: beyvra-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: Beyvra Loki
    uid: beyvra-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000

  - name: Beyvra Tempo
    uid: beyvra-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: beyvra-loki
        filterByTraceID: true
        filterBySpanID: true
      serviceMap:
        datasourceUid: beyvra-prometheus
