# Generated by Django 5.2.17 on 2026-08-04 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_credential_encryption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'real_wallet_assets',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'real_wallet_feature_flags',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'real_wallet_networks',
            },
        ),
        migrations.CreateModel(
            name='AssetNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('confirmations_required', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='real_wallet.asset')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='real_wallet.network')),
            ],
            options={
                'db_table': 'real_wallet_asset_networks',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
            ],
            options={
                'db_table': 'real_wallet_audit_events',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(max_length=32)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('account_code', models.CharField(max_length=64)),
                ('account_type', models.CharField(max_length=32)),
                ('normal_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_ledger_accounts', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_ledger_accounts',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('effective_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='real_wallet.ledgertransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_ledger_transactions', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_ledger_transactions',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='real_wallet.ledgeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.asset')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='real_wallet.ledgertransaction')),
            ],
            options={
                'db_table': 'real_ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
            ],
            options={
                'db_table': 'real_eventing_outbox',
            },
        ),
        migrations.CreateModel(
            name='RealWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ACTIVE', max_length=24)),
                ('restricted_reason', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_wallets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_wallets', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_wallet_wallets',
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('state', models.CharField(default='REQUESTED', max_length=24)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
                ('destination_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='real_wallet.realwallet')),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_wallet_transfers',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('output_index', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('state', models.CharField(default='DETECTED', max_length=32)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='real_wallet.ledgertransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_wallet_deposits',
            },
        ),
        migrations.CreateModel(
            name='BalanceHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('state', models.CharField(default='ACTIVE', max_length=16)),
                ('reason', models.CharField(max_length=64)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_ledger_holds',
            },
        ),
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_atomic', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('pending_credit_atomic', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('held_atomic', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('reserved_atomic', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_wallet_balances',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=255)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('fee_atomic', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('state', models.CharField(default='REQUESTED', max_length=40)),
                ('blockchain_transaction', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='real_wallet.balancehold')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_wallet_withdrawals',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
            ],
            options={
                'db_table': 'real_wallet_idempotency',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'actor', 'endpoint', 'method', 'key'), name='real_idempotency_scope_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'owner_type', 'owner_id', 'asset', 'account_code'), name='real_ledger_account_unique'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='real_ledger_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_atomic__gt', 0)), name='real_ledger_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetnetwork',
            constraint=models.UniqueConstraint(fields=('asset', 'network'), name='real_wallet_asset_network_unique'),
        ),
        migrations.AddConstraint(
            model_name='realwallet',
            constraint=models.UniqueConstraint(fields=('tenant', 'owner'), name='real_wallet_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='internaltransfer',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='real_transfer_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='internaltransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_atomic__gt', 0)), name='real_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(fields=('asset_network', 'transaction_hash', 'output_index'), name='real_deposit_chain_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='balancehold',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='real_hold_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='balancehold',
            constraint=models.CheckConstraint(condition=models.Q(('amount_atomic__gt', 0)), name='real_hold_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.UniqueConstraint(fields=('wallet', 'asset_network'), name='real_wallet_balance_unique'),
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.CheckConstraint(condition=models.Q(('posted_atomic__gte', 0)), name='real_wallet_posted_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.CheckConstraint(condition=models.Q(('pending_credit_atomic__gte', 0)), name='real_wallet_pending_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.CheckConstraint(condition=models.Q(('held_atomic__gte', 0)), name='real_wallet_held_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_atomic__gte', 0)), name='real_wallet_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='real_withdrawal_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('amount_atomic__gt', 0)), name='real_withdrawal_amount_positive'),
        ),
    ]
