# Generated by Django 5.2.17 on 2026-08-04 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_credential_encryption'),
        ('real_wallet', '0002_immutable_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'real_integration_webhook_deliveries',
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('connection_type', models.CharField(max_length=64)),
                ('encrypted_config', models.BinaryField()),
                ('status', models.CharField(default='DISABLED', max_length=24)),
                ('environment', models.CharField(default='sandbox', max_length=24)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_provider_connections', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_integration_provider_connections',
            },
        ),
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='real_wallet.webhookdelivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_webhook_events', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_integration_webhook_events',
            },
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='real_wallet.webhookevent'),
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500)),
                ('status', models.CharField(default='DISABLED', max_length=24)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_webhook_subscriptions', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_integration_webhook_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WebhookSecretVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_id', models.CharField(max_length=64)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_versions', to='real_wallet.webhooksubscription')),
            ],
            options={
                'db_table': 'real_integration_webhook_secret_versions',
            },
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='real_wallet.webhooksubscription'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_id'), name='real_webhook_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='webhooksecretversion',
            constraint=models.UniqueConstraint(fields=('subscription', 'key_id'), name='real_webhook_secret_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'event'), name='real_webhook_delivery_unique'),
        ),
    ]
