# Generated by Django 5.2.17 on 2026-08-05 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_credential_encryption'),
        ('real_wallet', '0003_webhookdelivery_providerconnection_webhookattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('risk_state', models.CharField(default='UNSCREENED', max_length=24)),
                ('cooling_until', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_withdrawal_addresses', to='integrations.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_addresses', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_wallet_withdrawal_addresses',
                'constraints': [models.UniqueConstraint(fields=('wallet', 'asset_network', 'address'), name='real_withdrawal_address_unique')],
            },
        ),
    ]
