# Generated by Django 5.2.17 on 2026-08-05 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_wallet', '0004_withdrawaladdress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='real_wallet.withdrawal')),
            ],
            options={
                'db_table': 'real_wallet_withdrawal_approvals',
                'constraints': [models.UniqueConstraint(fields=('withdrawal', 'approver'), name='real_withdrawal_approval_unique')],
            },
        ),
    ]
