# Generated by Django 5.2.17 on 2026-08-05 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_credential_encryption'),
        ('real_wallet', '0005_withdrawalapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('risk_level', models.CharField(default='UNKNOWN', max_length=16)),
                ('provider_case_reference', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='real_compliance_profile', to='integrations.organization')),
            ],
            options={
                'db_table': 'real_compliance_profiles',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=32)),
                ('status', models.CharField(default='RUNNING', max_length=24)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
            ],
            options={
                'db_table': 'real_reconciliation_runs',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('result', models.CharField(max_length=32)),
                ('internal_amount_atomic', models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True)),
                ('external_amount_atomic', models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='real_wallet.reconciliationrun')),
            ],
            options={
                'db_table': 'real_reconciliation_items',
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_restrictions', to='integrations.organization')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restrictions', to='real_wallet.realwallet')),
            ],
            options={
                'db_table': 'real_compliance_restrictions',
            },
        ),
        migrations.CreateModel(
            name='TransactionScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=16)),
                ('amount_atomic', models.DecimalField(decimal_places=0, max_digits=78)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('provider_case_reference', models.CharField(blank=True, max_length=255)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('asset_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_wallet.assetnetwork')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.organization')),
            ],
            options={
                'db_table': 'real_compliance_transaction_screenings',
            },
        ),
    ]
