# Generated by Django 5.2.17 on 2026-08-05 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_wallet', '0006_complianceprofile_reconciliationrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(default='RECEIVED', max_length=24)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_receipts', to='real_wallet.providerconnection')),
            ],
            options={
                'db_table': 'real_integration_provider_webhook_receipts',
                'constraints': [models.UniqueConstraint(fields=('connection', 'provider_event_id'), name='real_provider_event_unique')],
            },
        ),
    ]
