# Generated by Django 5.0.2 on 2024-08-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("image", models.ImageField(blank=True, null=True, upload_to="wallet_account_type_images")),
                ("is_fiat", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_crypto", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("balance", models.FloatField(default=0.0)),
                ("available_balance", models.FloatField(default=0.0)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "account_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="wallet.accounttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "account_type")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("D", "DEPOSIT"), ("W", "WITHDRAWAL"), ("TD", "TRADE"), ("TN", "TRANSFER")]
                    ),
                ),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "PENDING"), ("S", "SUCCESSFUL"), ("F", "FAILED"), ("R", "REFUNDED")]
                    ),
                ),
                ("gateway_ref", models.CharField(max_length=255)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="wallet.wallet")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
