# Generated by Django 5.0.2 on 2024-08-14 19:43

import django.db.models.deletion
import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=5, unique=True)),
                ("symbol", models.CharField(max_length=5, unique=True)),
                ("longer_name", models.CharField(max_length=25, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="accounttype",
            name="symbol",
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="wallet_account_type_images",
                validators=[wallet.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="currency",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to="wallet.currency"),
            preserve_default=False,
        ),
    ]
