# Generated by Django 5.0.2 on 2024-08-15 00:29

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_currency_remove_accounttype_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttype",
            name="image",
        ),
        migrations.RemoveField(
            model_name="accounttype",
            name="is_crypto",
        ),
        migrations.AddField(
            model_name="currency",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wallet.models.upload, validators=[wallet.models.validate_file_size]
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_crypto",
            field=models.BooleanField(default=False),
        ),
    ]
