# Generated by Django 5.0.2 on 2024-08-16 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_remove_accounttype_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "name")},
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to="wallet.currency"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="wallet.currency"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="available_balance",
        ),
        migrations.DeleteModel(
            name="AccountType",
        ),
    ]
