# Generated by Django 5.0.2 on 2024-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallet_unique_together_wallet_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
