# Generated by Django 5.0.2 on 2024-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
