# Generated by Django 5.0.2 on 2024-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_alter_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_real",
            field=models.BooleanField(default=True),
        ),
    ]
