# Generated by Django 5.0.2 on 2024-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_wallet_is_real"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gateway_ref",
        ),
    ]
