# Generated by Django 5.0.2 on 2024-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
