# Generated by Django 5.0.2 on 2024-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_transaction_description_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='longer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
