# Generated by Django 5.0.2 on 2024-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_currency_longer_name_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
