# Generated by Django 5.0.2 on 2024-10-02 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_transaction_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBalanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.CharField(blank=True, choices=[('CORRECTION', 'Correction'), ('BONUS', 'Bonus'), ('FEE', 'Fee Deduction'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
