# Generated by Django 5.0.2 on 2025-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_manualbalanceupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED'), ('R', 'REFUNDED')], max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('D', 'DEPOSIT'), ('W', 'WITHDRAWAL'), ('TD', 'TRADE'), ('TN', 'TRANSFER')], max_length=250),
        ),
    ]
