# Generated by Django 5.0.2 on 2024-09-28 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0001_initial'),
        ('wallet', '0012_alter_currency_longer_name_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name of the account holder', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='denial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='network_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='sender_contact_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='sender_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='txid',
            field=models.CharField(blank=True, help_text='Transaction reference ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='bank_account_app.bankaccount'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet'),
        ),
    ]
