# Generated by Django 5.0.2 on 2024-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0002_bankaccount_country_bankaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
