# Generated by Django 5.0.2 on 2024-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0003_alter_bankaccount_routing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='network_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
