# Generated by Django 5.2.16 on 2026-08-11 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('description_safe', models.TextField(blank=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=96, unique=True)),
                ('category', models.CharField(choices=[('MARKET_DATA', 'Market Data'), ('NEWS', 'News'), ('TRADING', 'Trading'), ('API', 'Api'), ('REPORTING', 'Reporting'), ('ANALYTICS', 'Analytics'), ('SUPPORT', 'Support'), ('FINANCIAL_FEATURE', 'Financial Feature'), ('OTHER', 'Other')], max_length=24)),
                ('description_safe', models.TextField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('fee_type', models.CharField(choices=[('TRADING_COMMISSION', 'TRADING_COMMISSION'), ('MAKER', 'MAKER'), ('TAKER', 'TAKER'), ('WITHDRAWAL', 'WITHDRAWAL'), ('DEPOSIT', 'DEPOSIT'), ('TRANSFER', 'TRANSFER'), ('EXCHANGE_PASS_THROUGH', 'EXCHANGE_PASS_THROUGH'), ('BROKER_PASS_THROUGH', 'BROKER_PASS_THROUGH'), ('REGULATORY', 'REGULATORY'), ('SUBSCRIPTION', 'SUBSCRIPTION'), ('OTHER', 'OTHER')], max_length=32)),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('currency', models.CharField(max_length=12)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('entity_ref', models.CharField(max_length=128)),
                ('actor_ref', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('evidence_hash', models.CharField(max_length=64)),
                ('metadata_safe', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRoundingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=12)),
                ('decimal_places', models.PositiveSmallIntegerField()),
                ('rounding_mode', models.CharField(max_length=24)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pricing_authority.accountplan')),
            ],
        ),
        migrations.CreateModel(
            name='AccountPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_ref', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=16)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plan_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.accountplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE'), ('LIMIT_OVERRIDE', 'LIMIT_OVERRIDE')], max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('reason_code', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_entitlement_overrides', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.entitlement')),
            ],
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(blank=True, max_length=24)),
                ('instrument_ref', models.UUIDField(blank=True, null=True)),
                ('venue_ref', models.CharField(blank=True, max_length=64)),
                ('side', models.CharField(blank=True, max_length=8)),
                ('order_type', models.CharField(blank=True, max_length=24)),
                ('jurisdiction', models.CharField(blank=True, max_length=8)),
                ('min_notional', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('max_notional', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('rate_type', models.CharField(choices=[('FLAT', 'FLAT'), ('PERCENT', 'PERCENT'), ('BASIS_POINTS', 'BASIS_POINTS'), ('PER_SHARE', 'PER_SHARE'), ('PER_CONTRACT', 'PER_CONTRACT'), ('PER_UNIT', 'PER_UNIT'), ('TIERED', 'TIERED')], max_length=16)),
                ('rate_value', models.DecimalField(decimal_places=12, max_digits=30)),
                ('min_fee', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('currency', models.CharField(max_length=12)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('rule_version', models.PositiveIntegerField()),
                ('is_rebate', models.BooleanField(default=False)),
                ('account_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.accountplan')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='pricing_authority.feeschedule')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=96)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('audit_ref', models.UUIDField(default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_fee_waivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('limit_value', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('limit_unit', models.CharField(blank=True, max_length=32)),
                ('metadata_safe', models.JSONField(blank=True, default=dict)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.entitlement')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='pricing_authority.accountplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('promotion_type', models.CharField(max_length=24)),
                ('value', models.DecimalField(decimal_places=12, max_digits=30)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('eligible_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.accountplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('ANNUAL', 'ANNUAL'), ('CUSTOM', 'CUSTOM')], max_length=16)),
                ('currency', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=30)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing_authority.accountplanversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='pricing_plan_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='accountplanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('status', 'ACTIVE')), fields=('account',), name='pricing_one_current_assignment'),
        ),
        migrations.AddIndex(
            model_name='feerule',
            index=models.Index(fields=['asset_class', 'effective_from'], name='pricing_fee_lookup'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('plan_version', 'entitlement'), name='pricing_plan_entitlement_unique'),
        ),
    ]
