# Generated by Django 5.0.2 on 2025-01-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('good', 'Good'), ('issue', 'Issue')], max_length=20)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
