# Generated by Django 5.0.2 on 2025-01-28 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_systemhealth_alter_revenue_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['date'], name='reporting_r_date_58519e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['amount'], name='reporting_r_amount_1c71b4_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user'], name='reporting_t_user_id_edb2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset'], name='reporting_t_asset_0fb2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_volume'], name='reporting_t_trade_v_5f8683_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_date'], name='reporting_t_trade_d_951136_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='reporting_t_user_id_882db1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='reporting_t_amount_2ac527_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='reporting_t_date_8afaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='reporting_t_transac_0e8cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='reporting_t_categor_134c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user'], name='reporting_u_user_id_4312f4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['is_active'], name='reporting_u_is_acti_0125da_idx'),
        ),
    ]
