# Generated by Django 5.2.16 on 2026-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='eligibility_evaluated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='eligibility_policy_version',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='eligibility_reason_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='eligibility_result',
            field=models.CharField(default='DENIED', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='simulation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant_ref', 'subject_ref', 'idempotency_key'), name='unique_sim_order_idempotency'),
        ),
    ]
