# Generated by Django 5.2.16 on 2026-08-11 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0005_executionproviderhealth_executionreconciliationrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionGovernanceChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('requested_by_ref', models.CharField(max_length=128)),
                ('reviewed_by_ref', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_changes', to='canonical_trading.executionproviderrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('provider', 'action'), name='one_pending_execution_governance_change')],
            },
        ),
    ]
