# Generated by Django 5.2.16 on 2026-08-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0006_executiongovernancechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionroutingdecision',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='executionroutingdecision',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='canonical_trading.executionroutingdecision'),
        ),
        migrations.AddConstraint(
            model_name='executionroutingdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'revision'), name='execution_route_order_revision_unique'),
        ),
    ]
