# Generated by Django 5.2.16 on 2026-08-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0007_executionroutingdecision_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionqualityreport',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='executionqualityreport',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='canonical_trading.executionqualityreport'),
        ),
        migrations.AlterField(
            model_name='executionqualityreport',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_quality_reports', to='canonical_trading.tradingorder'),
        ),
        migrations.AddConstraint(
            model_name='executionqualityreport',
            constraint=models.UniqueConstraint(fields=('order', 'revision'), name='execution_quality_order_revision_unique'),
        ),
    ]
