# Generated by Django 5.2.17 on 2026-09-12 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_paper_accounts(apps, schema_editor):
    Projection = apps.get_model("canonical_trading", "SimulatedAccount")
    Account = apps.get_model("canonical_trading", "TradingAccount")
    database = schema_editor.connection.alias
    for projection in Projection.objects.using(database).iterator(chunk_size=500):
        Account.objects.using(database).create(
            id=projection.id,
            tenant_ref=projection.tenant_ref,
            subject_ref=projection.subject_ref,
            account_ref=projection.account_ref,
            execution_mode="PAPER",
            base_currency=projection.quote_currency,
            status=projection.status,
            trading_enabled=projection.status == "ACTIVE",
            funding_enabled=False,
            withdrawals_enabled=False,
            paper_projection_id=projection.id,
        )
        Account.objects.using(database).filter(pk=projection.id).update(
            created_at=projection.created_at, updated_at=projection.updated_at
        )


class Migration(migrations.Migration):
    dependencies = [
        ("canonical_trading", "0009_merge_converged_trading_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_ref", models.CharField(max_length=128)),
                ("subject_ref", models.CharField(max_length=128)),
                ("account_ref", models.CharField(max_length=128)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("PAPER", "Paper"), ("LIVE", "Live")], max_length=5
                    ),
                ),
                ("base_currency", models.CharField(default="USD", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("RESTRICTED", "Restricted"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("trading_enabled", models.BooleanField(default=False)),
                ("funding_enabled", models.BooleanField(default=False)),
                ("withdrawals_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper_projection",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trading_account",
                        to="canonical_trading.simulatedaccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_ref", "subject_ref", "account_ref"),
                        name="trading_account_scope_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "PENDING",
                                    "ACTIVE",
                                    "RESTRICTED",
                                    "SUSPENDED",
                                    "CLOSED",
                                ],
                            )
                        ),
                        name="trading_account_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("execution_mode", "PAPER"),
                                ("funding_enabled", False),
                                ("paper_projection__isnull", False),
                                ("withdrawals_enabled", False),
                            ),
                            models.Q(
                                ("execution_mode", "LIVE"),
                                ("paper_projection__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="trading_account_mode_boundary",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_paper_accounts, migrations.RunPython.noop),
    ]
