# Generated by Django 5.2.17 on 2026-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0011_account_identity_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PREVIEWED', 'PREVIEWED'), ('PENDING_SUBMIT', 'PENDING_SUBMIT'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('OPEN', 'OPEN'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCEL_PENDING', 'CANCEL_PENDING'), ('CANCELLED', 'CANCELLED'), ('CANCELED', 'CANCELED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('UNKNOWN', 'UNKNOWN'), ('RECONCILIATION_REQUIRED', 'RECONCILIATION_REQUIRED')], default='PENDING', max_length=24),
        ),
    ]
