# Generated by Django 5.2.17 on 2026-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0011_account_identity_boundary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingorder',
            name='unique_sim_order_idempotency',
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='fee_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=36),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='fee_schedule_version',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='price_observation_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='price_observed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='price_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='price_stale_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='reference_price',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='tradingorder',
            index=models.Index(fields=['tenant_ref', 'account_ref', '-created_at'], name='sim_order_tenant_account_time'),
        ),
        migrations.AddIndex(
            model_name='tradingorder',
            index=models.Index(fields=['tenant_ref', 'instrument_id', '-created_at'], name='sim_order_tenant_instrument'),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant_ref', 'account_ref', 'idempotency_key'), name='unique_sim_order_idempotency'),
        ),
    ]
