# Generated by Django 5.2.17 on 2026-09-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0012_mission1_trading_authorities'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='simulatedaccount',
            constraint=models.CheckConstraint(condition=models.Q(('total_balance__gte', 0)), name='sim_account_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='simulatedaccount',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance__gte', 0)), name='sim_account_pending_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='simulatedposition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='sim_position_long_only'),
        ),
        migrations.AddConstraint(
            model_name='simulatedreservation',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='sim_reservation_original_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='simulatedreservation',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0), ('remaining_amount__lte', models.F('original_amount'))), name='sim_reservation_remaining_valid'),
        ),
        migrations.AddConstraint(
            model_name='simulatedtrade',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sim_trade_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='simulatedtrade',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='sim_trade_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sim_order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.CheckConstraint(condition=models.Q(('filled_quantity__gte', 0), ('filled_quantity__lte', models.F('quantity'))), name='sim_order_fill_in_range'),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('limit_price__isnull', True), ('order_type', 'MARKET')), models.Q(('limit_price__gt', 0), ('order_type', 'LIMIT')), _connector='OR'), name='sim_order_type_price_valid'),
        ),
        migrations.AddConstraint(
            model_name='tradingorder',
            constraint=models.CheckConstraint(condition=models.Q(('reference_price__isnull', True), ('reference_price__gt', 0), _connector='OR'), name='sim_order_reference_positive'),
        ),
    ]
