# Generated by Django 5.2.17 on 2026-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0013_mission1_database_invariants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatedreservation',
            name='asset',
            field=models.CharField(max_length=64),
        ),
    ]
