# Generated by Django 5.2.17 on 2026-09-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_trading', '0014_canonical_reservation_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedtrade',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=36),
        ),
    ]
