"""Provider-neutral integration contracts.

These interfaces describe capability boundaries only.  Importing this module
never enables a provider or performs network or financial I/O.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Mapping, Protocol, Sequence


class ProviderMode(str, Enum):
    SIMULATION = "SIMULATION"
    PAPER = "PAPER"
    LIVE = "LIVE"


class ProviderHealth(str, Enum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


class RoutingDecision(str, Enum):
    SIMULATION = "SIMULATION"
    DENIED = "DENIED"


@dataclass(frozen=True)
class ProviderCapabilities:
    provider_id: str
    operations: frozenset[str]
    asset_classes: frozenset[str] = frozenset()
    order_types: frozenset[str] = frozenset()


@dataclass(frozen=True)
class ExecutionRoutingPolicy:
    provider_id: str
    asset_class: str
    enabled: bool = False
    priority: int = 100
    max_notional: str = "0"
    supported_order_types: frozenset[str] = frozenset()
    staging_approved: bool = False
    production_approved: bool = False


class ExecutionProvider(Protocol):
    def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    def preview_order(self, order: Mapping) -> Mapping: ...
    def submit_order(self, order: Mapping, idempotency_key: str) -> Mapping: ...
    def cancel_order(self, provider_order_id: str, idempotency_key: str) -> Mapping: ...
    def replace_order(self, provider_order_id: str, changes: Mapping, idempotency_key: str) -> Mapping: ...
    def get_order(self, provider_order_id: str) -> Mapping: ...
    def list_orders(self, account_ref: str) -> Sequence[Mapping]: ...
    def get_executions(self, account_ref: str) -> Sequence[Mapping]: ...


class FixExecutionGateway(Protocol):
    def logon(self) -> None: ...
    def heartbeat(self) -> None: ...
    def new_order_single(self, message: Mapping) -> str: ...
    def cancel(self, message: Mapping) -> str: ...
    def replace(self, message: Mapping) -> str: ...
    def recover(self, begin_sequence: int, end_sequence: int) -> None: ...
    def logout(self) -> None: ...


class BankingProvider(Protocol):
    def link_account(self, request: Mapping) -> Mapping: ...
    def verify_account(self, provider_account_ref: str) -> Mapping: ...
    def create_funding_intent(self, request: Mapping, idempotency_key: str) -> Mapping: ...
    def transaction_status(self, operation_ref: str) -> Mapping: ...


class PaymentRailProvider(Protocol):
    def create_funding_intent(self, request: Mapping, idempotency_key: str) -> Mapping: ...
    def get_funding_status(self, operation_ref: str) -> Mapping: ...
    def create_payout(self, request: Mapping, idempotency_key: str) -> Mapping: ...
    def get_payout_status(self, operation_ref: str) -> Mapping: ...


class CustodyProvider(Protocol):
    def create_deposit_destination(self, request: Mapping, idempotency_key: str) -> Mapping: ...
    def get_balance(self, account_ref: str) -> Mapping: ...
    def get_deposit(self, operation_ref: str) -> Mapping: ...
    def validate_withdrawal(self, request: Mapping) -> Mapping: ...
    def submit_withdrawal(self, request: Mapping, idempotency_key: str) -> Mapping: ...
    def get_withdrawal(self, operation_ref: str) -> Mapping: ...


class ComplianceProvider(Protocol):
    def create_verification_session(self, request: Mapping) -> Mapping: ...
    def get_verification(self, provider_ref: str) -> Mapping: ...
    def screen_identity(self, request: Mapping) -> Mapping: ...
    def get_status(self, provider_ref: str) -> Mapping: ...
    def health(self) -> ProviderHealth: ...


class NotificationProvider(Protocol):
    def send(self, channel: str, message: Mapping, idempotency_key: str) -> Mapping: ...
    def status(self, provider_message_ref: str) -> Mapping: ...


class TaxReportingProvider(Protocol):
    def calculate_cost_basis(self, request: Mapping) -> Mapping: ...
    def generate_tax_lot_report(self, request: Mapping) -> Mapping: ...
    def generate_tax_document(self, request: Mapping) -> Mapping: ...


class ExecutionRouter:
    """Current routing authority: simulation or denial, never live/paper."""

    def route(self, *, simulation_authorized: bool, incident_active: bool,
              market_data_fresh: bool, requested_mode: ProviderMode) -> RoutingDecision:
        if incident_active or not simulation_authorized or not market_data_fresh:
            return RoutingDecision.DENIED
        if requested_mode is not ProviderMode.SIMULATION:
            return RoutingDecision.DENIED
        return RoutingDecision.SIMULATION

