# Generated by Django 5.2.16 on 2026-08-11 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralPolicy',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.CharField(max_length=32)),
                ('network', models.CharField(blank=True, max_length=64)),
                ('eligible', models.BooleanField(default=False)),
                ('haircut_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('valuation_currency', models.CharField(max_length=12)),
                ('max_concentration_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExposureLimit',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=24)),
                ('scope_ref', models.CharField(max_length=128)),
                ('limit_type', models.CharField(max_length=40)),
                ('limit_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('asset_class', models.CharField(blank=True, max_length=24)),
                ('instrument_id', models.UUIDField(blank=True, null=True)),
                ('venue_id', models.CharField(blank=True, max_length=64)),
                ('side', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidationPolicy',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority_method', models.CharField(max_length=40)),
                ('target_margin_ratio', models.DecimalField(decimal_places=10, max_digits=20)),
                ('minimum_buffer', models.DecimalField(decimal_places=10, max_digits=30)),
                ('max_orders_per_cycle', models.PositiveIntegerField()),
                ('max_notional_per_cycle', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarginPolicy',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('asset_class', models.CharField(max_length=24)),
                ('instrument_id', models.UUIDField(blank=True, null=True)),
                ('account_plan', models.CharField(blank=True, max_length=64)),
                ('jurisdiction', models.CharField(blank=True, max_length=8)),
                ('initial_margin_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('maintenance_margin_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('short_margin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('intraday_margin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('overnight_margin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('account_ref', models.CharField(max_length=128)),
                ('entity_ref', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('evidence_hash', models.CharField(max_length=64)),
                ('metadata_safe', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='PROPOSED', max_length=32)),
                ('trigger_reason', models.CharField(max_length=96)),
                ('required_reduction', models.DecimalField(decimal_places=10, max_digits=30)),
                ('currency', models.CharField(max_length=12)),
                ('target_margin_ratio', models.DecimalField(decimal_places=10, max_digits=20)),
                ('policy_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('simulation', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidation_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.UUIDField()),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('estimated_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('estimated_notional', models.DecimalField(decimal_places=10, max_digits=30)),
                ('priority', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=96)),
                ('state', models.CharField(default='PROPOSED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='risk_authority.liquidationplan')),
            ],
        ),
        migrations.CreateModel(
            name='MarginCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='OPEN', max_length=24)),
                ('triggered_at', models.DateTimeField()),
                ('required_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('currency', models.CharField(max_length=12)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reason_codes', models.JSONField(default=list)),
                ('policy_version', models.PositiveIntegerField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=64)),
                ('simulation', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margin_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ('OPEN', 'NOTIFIED', 'ACKNOWLEDGED', 'ESCALATED', 'LIQUIDATION_ELIGIBLE'))), fields=('account',), name='risk_one_active_margin_call')],
            },
        ),
    ]
