import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Organization", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=160)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="DemoAccount", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("account_type", models.CharField(default="DEMO", editable=False, max_length=8)), ("currency", models.CharField(default="USD", editable=False, max_length=3)), ("withdrawable", models.BooleanField(default=False, editable=False)), ("transferable", models.BooleanField(default=False, editable=False)), ("real_money", models.BooleanField(default=False, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="demo_accounts", to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="demo_accounts", to="integrations.organization"))]),
        migrations.CreateModel(name="IntegrationAuditEvent", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("action", models.CharField(max_length=100)), ("correlation_id", models.UUIDField(default=uuid.uuid4)), ("metadata", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="integrations.organization"))]),
        migrations.CreateModel(name="CRMConnection", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=120)), ("provider", models.CharField(choices=[("generic_webhook", "Generic HTTPS webhook"), ("odoo", "Odoo adapter")], default="generic_webhook", max_length=32)), ("endpoint", models.URLField(max_length=500)), ("secret_encrypted", models.TextField()), ("field_mapping", models.JSONField(blank=True, default=dict)), ("event_categories", models.JSONField(blank=True, default=list)), ("is_active", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="crm_connections", to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crm_connections", to="integrations.organization"))]),
        migrations.CreateModel(name="OrganizationMembership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(default="member", max_length=32)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="integrations.organization")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="ServiceToken", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("token_hash", models.CharField(max_length=64, unique=True)), ("name", models.CharField(max_length=120)), ("scopes", models.JSONField(default=list)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("expires_at", models.DateTimeField(blank=True, null=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_tokens", to="integrations.organization"))]),
        migrations.CreateModel(name="UserImport", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("status", models.CharField(choices=[("UPLOADED", "Uploaded"), ("COMMITTED", "Committed"), ("PROCESSING", "Processing"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("FAILED", "Failed")], default="UPLOADED", max_length=16)), ("file_name", models.CharField(max_length=255)), ("row_count", models.PositiveIntegerField(default=0)), ("valid_count", models.PositiveIntegerField(default=0)), ("invalid_count", models.PositiveIntegerField(default=0)), ("idempotency_key", models.CharField(max_length=255)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_imports", to="integrations.organization"))]),
        migrations.CreateModel(name="UserImportRow", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("row_number", models.PositiveIntegerField()), ("data", models.JSONField(default=dict)), ("errors", models.JSONField(blank=True, default=list)), ("status", models.CharField(default="VALID", max_length=16)), ("import_job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="integrations.userimport")), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="DemoLedgerEntry", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("entry_type", models.CharField(default="DEMO_INITIAL_CREDIT", editable=False, max_length=40)), ("amount_cents", models.PositiveIntegerField(default=200000, editable=False)), ("currency", models.CharField(default="USD", editable=False, max_length=3)), ("reference", models.CharField(editable=False, max_length=255, unique=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="integrations.demoaccount"))], options={"constraints": [models.UniqueConstraint(fields=("account", "entry_type"), name="one_demo_initial_credit")]}),
        migrations.CreateModel(name="ExternalIdentity", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("external_user_id", models.CharField(max_length=255)), ("source", models.CharField(default="third_party_crm", max_length=80)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_identities", to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="integrations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "external_user_id"), name="unique_external_identity")]}),
        migrations.AddConstraint(model_name="demoaccount", constraint=models.UniqueConstraint(fields=("user", "organization"), name="one_demo_account_per_user_org")),
        migrations.AddConstraint(model_name="organizationmembership", constraint=models.UniqueConstraint(fields=("user", "organization"), name="unique_org_membership")),
        migrations.AddConstraint(model_name="userimport", constraint=models.UniqueConstraint(fields=("organization", "idempotency_key"), name="unique_import_idempotency")),
        migrations.AddConstraint(model_name="userimportrow", constraint=models.UniqueConstraint(fields=("import_job", "row_number"), name="unique_import_row")),
    ]
