# Generated by Django 5.2.16 on 2026-08-11 08:22

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("topic", models.CharField(max_length=80)),
                ("payload_safe", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "audit_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("role", models.CharField(blank=True, max_length=40)),
                ("action", models.CharField(max_length=64)),
                ("target", models.CharField(max_length=128)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("before_state_hash", models.CharField(blank=True, max_length=64)),
                ("after_state_hash", models.CharField(blank=True, max_length=64)),
                ("metadata_safe", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceIdentity",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "device_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("device_class", models.CharField(max_length=40)),
                ("trusted", models.BooleanField(default=False)),
                ("revoked", models.BooleanField(default=False)),
                ("risk_state", models.CharField(default="UNKNOWN", max_length=16)),
                ("fingerprint_hash", models.CharField(max_length=64)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountSession",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "session_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("auth_strength", models.CharField(default="PASSWORD", max_length=24)),
                ("mfa_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "device_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.deviceidentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FraudCase",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "case_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("case_type", models.CharField(max_length=64)),
                ("risk_level", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("IN_REVIEW", "IN_REVIEW"),
                            ("ESCALATED", "ESCALATED"),
                            ("RESOLVED", "RESOLVED"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("reason_codes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "notification_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=48)),
                ("category", models.CharField(max_length=16)),
                ("severity", models.CharField(default="INFO", max_length=12)),
                ("channel", models.CharField(max_length=12)),
                ("template_version", models.CharField(max_length=32)),
                ("payload_safe", models.JSONField(default=dict)),
                ("status", models.CharField(default="QUEUED", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("failure_reason_safe", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("category", models.CharField(max_length=16)),
                ("channel", models.CharField(max_length=12)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatorActionRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("action_type", models.CharField(max_length=64)),
                ("target_ref", models.CharField(max_length=128)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=500)),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperatorRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("role", models.CharField(max_length=40)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyExportJob",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "job_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="QUEUED", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("artifact_ref", models.CharField(blank=True, max_length=255)),
                ("policy_version", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("consumer", models.CharField(max_length=80)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("event_id", "consumer"), name="unique_inbox_effect")],
            },
        ),
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "job_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("report_type", models.CharField(max_length=32)),
                ("parameters_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("status", models.CharField(default="QUEUED", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("artifact_ref", models.CharField(blank=True, max_length=255)),
                ("reconciliation_passed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "event_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "LOGIN_SUCCESS"),
                            ("LOGIN_FAILURE", "LOGIN_FAILURE"),
                            ("PASSWORD_RESET", "PASSWORD_RESET"),
                            ("MFA_ENABLED", "MFA_ENABLED"),
                            ("MFA_DISABLED", "MFA_DISABLED"),
                            ("MFA_RESET", "MFA_RESET"),
                            ("SESSION_CREATED", "SESSION_CREATED"),
                            ("SESSION_REVOKED", "SESSION_REVOKED"),
                            ("NEW_DEVICE", "NEW_DEVICE"),
                            ("NEW_NETWORK", "NEW_NETWORK"),
                            ("ACCOUNT_LOCKED", "ACCOUNT_LOCKED"),
                            ("ACCOUNT_UNLOCKED", "ACCOUNT_UNLOCKED"),
                            ("WITHDRAWAL_ATTEMPT", "WITHDRAWAL_ATTEMPT"),
                            ("SUSPICIOUS_ACTIVITY", "SUSPICIOUS_ACTIVITY"),
                        ],
                        max_length=40,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("source", models.CharField(max_length=80)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("LOW", "LOW"), ("MEDIUM", "MEDIUM"), ("HIGH", "HIGH"), ("CRITICAL", "CRITICAL")],
                        max_length=10,
                    ),
                ),
                ("device_ref", models.UUIDField(blank=True, null=True)),
                ("network_ref", models.CharField(blank=True, max_length=128)),
                ("session_ref", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(default=operations.models.uuid4, editable=False)),
                ("metadata_safe", models.JSONField(default=dict)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("statement_id", models.UUIDField(default=operations.models.uuid4, editable=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("simulation", models.BooleanField(default=True)),
                ("reconciliation_passed", models.BooleanField(default=False)),
                ("correction_reason", models.CharField(blank=True, max_length=500)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="operations.statement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportCase",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "case_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_ACCESS", "ACCOUNT_ACCESS"),
                            ("TRADING", "TRADING"),
                            ("MARKET_DATA", "MARKET_DATA"),
                            ("DEMO", "DEMO"),
                            ("PAYMENTS", "PAYMENTS"),
                            ("WITHDRAWAL", "WITHDRAWAL"),
                            ("DEPOSIT", "DEPOSIT"),
                            ("COMPLIANCE", "COMPLIANCE"),
                            ("SECURITY", "SECURITY"),
                            ("BUG", "BUG"),
                            ("TECHNICAL", "TECHNICAL"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=24,
                    ),
                ),
                ("priority", models.CharField(default="NORMAL", max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("PENDING_CUSTOMER", "PENDING_CUSTOMER"),
                            ("PENDING_INTERNAL", "PENDING_INTERNAL"),
                            ("ESCALATED", "ESCALATED"),
                            ("RESOLVED", "RESOLVED"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("assigned_team", models.CharField(blank=True, max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("safe_summary", models.CharField(max_length=500)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupportCaseEvent",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "event_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_VISIBLE_MESSAGE", "CUSTOMER_VISIBLE_MESSAGE"),
                            ("INTERNAL_NOTE", "INTERNAL_NOTE"),
                        ],
                        max_length=24,
                    ),
                ),
                ("body_safe", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="operations.supportcase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionHistoryEntry",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "entry_id",
                    models.UUIDField(
                        default=operations.models.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("asset", models.CharField(max_length=24)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                ("fee", models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ("status", models.CharField(max_length=24)),
                ("occurred_at", models.DateTimeField()),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("source_ref", models.CharField(max_length=128)),
                ("simulation", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-entry_id"),
            },
        ),
        migrations.CreateModel(
            name="AccountFreeze",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "level",
                    models.CharField(
                        choices=[("NONE", "NONE"), ("PARTIAL", "PARTIAL"), ("FULL", "FULL")],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("review_evidence", models.JSONField(default=dict)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="freeze_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("tenant_id", "account"),
                        name="one_active_freeze",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="deviceidentity",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "account", "fingerprint_hash"), name="unique_safe_device"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "account", "channel", "dedup_key"), name="unique_notification_effect"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "account", "category", "channel"), name="unique_notification_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatorrole",
            constraint=models.UniqueConstraint(fields=("user", "tenant_id", "role"), name="unique_operator_role"),
        ),
        migrations.AddConstraint(
            model_name="privacyexportjob",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "account", "idempotency_key"), name="unique_privacy_export"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportjob",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "account", "idempotency_key"), name="unique_report_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="statement",
            constraint=models.UniqueConstraint(fields=("statement_id", "version"), name="unique_statement_version"),
        ),
    ]
