# Generated by Django 5.2.16 on 2026-08-11 08:46

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationCheck",
            fields=[
                (
                    "check_id",
                    models.UUIDField(
                        default=operations.models.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                ("domain", models.CharField(max_length=24)),
                ("status", models.CharField(max_length=16)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("details_safe", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("-checked_at",),
            },
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                ("tenant_id", models.CharField(db_index=True, max_length=120)),
                (
                    "request_id",
                    models.UUIDField(
                        default=operations.models.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="PENDING_REVIEW", max_length=24)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_version",
                    models.CharField(default="PENDING-LEGAL-APPROVAL", max_length=32),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("retained_categories", models.JSONField(default=list)),
                ("anonymized_categories", models.JSONField(default=list)),
                ("blocked_by_legal_hold", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "account", "idempotency_key"),
                        name="unique_deletion_request",
                    )
                ],
            },
        ),
    ]
