# Generated by Django 5.2.16 on 2026-08-11 10:38

import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_trading_halt_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistoryentry',
            name='type',
            field=models.CharField(choices=[('ORDER', 'ORDER'), ('TRADE', 'TRADE'), ('FEE', 'FEE'), ('DEPOSIT', 'DEPOSIT'), ('WITHDRAWAL', 'WITHDRAWAL'), ('TRANSFER', 'TRANSFER'), ('ADJUSTMENT', 'ADJUSTMENT'), ('RESERVATION', 'RESERVATION'), ('SETTLEMENT', 'SETTLEMENT')], max_length=20),
        ),
        migrations.CreateModel(
            name='TradeConfirmation',
            fields=[
                ('tenant_id', models.CharField(db_index=True, max_length=120)),
                ('trade_id', models.UUIDField(default=operations.models.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_ref', models.CharField(max_length=128)),
                ('instrument', models.CharField(max_length=64)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=36)),
                ('price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('fee', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('executed_at', models.DateTimeField()),
                ('simulation', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-executed_at', '-trade_id'),
            },
        ),
    ]
