# Generated by Django 5.2.16 on 2026-08-11 08:10

import apps.compliance.domain
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_credential_encryption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProviderGovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(default='DISABLED', max_length=32)),
                ('capabilities', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCase',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_REVIEW', 'IN_REVIEW'), ('ESCALATED', 'ESCALATED'), ('RESOLVED_APPROVED', 'RESOLVED_APPROVED'), ('RESOLVED_REJECTED', 'RESOLVED_REJECTED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=24)),
                ('priority', models.CharField(default='NORMAL', max_length=16)),
                ('reason_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, default='', max_length=64)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCaseEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='canonical_compliance.compliancecase')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceInboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_compliance_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_state', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('RESTRICTED', 'RESTRICTED'), ('SUSPENDED', 'SUSPENDED'), ('CLOSED', 'CLOSED')], default=apps.compliance.domain.AccountState['PENDING'], max_length=16)),
                ('kyc_state', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('PENDING', 'PENDING'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('REQUIRES_UPDATE', 'REQUIRES_UPDATE')], default=apps.compliance.domain.KycState['NOT_STARTED'], max_length=20)),
                ('aml_state', models.CharField(choices=[('NOT_SCREENED', 'NOT_SCREENED'), ('PENDING', 'PENDING'), ('CLEARED', 'CLEARED'), ('REVIEW_REQUIRED', 'REVIEW_REQUIRED'), ('BLOCKED', 'BLOCKED')], default=apps.compliance.domain.AmlState['NOT_SCREENED'], max_length=20)),
                ('sanctions_state', models.CharField(choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CLEAR', 'CLEAR'), ('POSSIBLE_MATCH', 'POSSIBLE_MATCH'), ('CONFIRMED_MATCH', 'CONFIRMED_MATCH'), ('MANUAL_REVIEW', 'MANUAL_REVIEW')], default=apps.compliance.domain.SanctionsState['NOT_CHECKED'], max_length=20)),
                ('jurisdiction_state', models.CharField(choices=[('SUPPORTED', 'SUPPORTED'), ('LIMITED', 'LIMITED'), ('RESTRICTED', 'RESTRICTED'), ('UNKNOWN', 'UNKNOWN')], default=apps.compliance.domain.JurisdictionState['UNKNOWN'], max_length=16)),
                ('jurisdiction_evidence_ref', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('kyc_expires_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_next_review_at', models.DateTimeField(blank=True, null=True)),
                ('aml_next_review_at', models.DateTimeField(blank=True, null=True)),
                ('jurisdiction_next_review_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profiles', to='integrations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceOverride',
            fields=[
                ('override_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control', models.CharField(max_length=40)),
                ('previous_state', models.CharField(max_length=64)),
                ('new_state', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_overrides_requested', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceOutboxEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.AddField(
            model_name='compliancecase',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='canonical_compliance.complianceprofile'),
        ),
        migrations.CreateModel(
            name='ComplianceAuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('actor_ref', models.CharField(blank=True, default='SYSTEM', max_length=128)),
                ('reason_codes', models.JSONField(default=list)),
                ('state_before', models.JSONField(default=dict)),
                ('state_after', models.JSONField(default=dict)),
                ('policy_version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountRestriction',
            fields=[
                ('restriction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restriction_type', models.CharField(choices=[('TRADING_DISABLED', 'TRADING_DISABLED'), ('DEPOSITS_DISABLED', 'DEPOSITS_DISABLED'), ('WITHDRAWALS_DISABLED', 'WITHDRAWALS_DISABLED'), ('TRANSFERS_DISABLED', 'TRANSFERS_DISABLED'), ('MARKET_DATA_LIMITED', 'MARKET_DATA_LIMITED'), ('ACCOUNT_READ_ONLY', 'ACCOUNT_READ_ONLY'), ('MANUAL_REVIEW_REQUIRED', 'MANUAL_REVIEW_REQUIRED')], max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_restrictions_created', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('user_action', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityDecision',
            fields=[
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(max_length=16)),
                ('result', models.CharField(max_length=20)),
                ('reason_codes', models.JSONField(default=list)),
                ('policy_version', models.CharField(max_length=32)),
                ('evaluated_at', models.DateTimeField()),
                ('context_ref', models.CharField(blank=True, default='', max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_decisions', to='canonical_compliance.complianceprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='complianceprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_compliance_profile_org_user'),
        ),
        migrations.AddIndex(
            model_name='accountrestriction',
            index=models.Index(fields=['account', 'active', 'restriction_type'], name='restriction_active_idx'),
        ),
    ]
