# Generated by Django 5.2.16 on 2026-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceoverride',
            name='control',
            field=models.CharField(max_length=80),
        ),
    ]
