# Generated by Django 5.0.2 on 2024-08-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssetCategory",
            new_name="TradeCategory",
        ),
    ]
