# Generated by Django 5.0.2 on 2024-08-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_rename_assetcategory_tradecategory"),
        ("wallet", "0007_wallet_is_real"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="user",
        ),
        migrations.AddField(
            model_name="trade",
            name="wallet",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="trades", to="wallet.wallet"
            ),
            preserve_default=False,
        ),
    ]
