# Generated by Django 5.0.2 on 2024-08-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_remove_trade_user_trade_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="net",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
