# Generated by Django 5.0.2 on 2024-08-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_trade_net_alter_trade_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="net",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
