from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("trade", "0011_demoeventoutbox")]
    operations = [
        migrations.CreateModel(name="CanonicalQuote", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("instrument_id",models.CharField(max_length=64)),("bid",models.DecimalField(decimal_places=12,max_digits=30,null=True)),("ask",models.DecimalField(decimal_places=12,max_digits=30,null=True)),("bid_size",models.DecimalField(decimal_places=12,max_digits=30,null=True)),("ask_size",models.DecimalField(decimal_places=12,max_digits=30,null=True)),("last",models.DecimalField(decimal_places=12,max_digits=30,null=True)),("provider_timestamp",models.DateTimeField()),("received_at",models.DateTimeField()),("provider_id",models.CharField(max_length=64)),("sequence",models.CharField(blank=True,max_length=128)),("delayed",models.BooleanField(default=False)),("suspect",models.BooleanField(default=False)),("provenance",models.JSONField(default=dict))], options={"indexes":[models.Index(fields=["instrument_id","-provider_timestamp"],name="canonical_quote_latest_idx")],"constraints":[models.UniqueConstraint(fields=("provider_id","instrument_id","provider_timestamp","sequence"),name="canonical_quote_identity")]}),
        migrations.CreateModel(name="CanonicalTradeTick", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("instrument_id",models.CharField(max_length=64)),("price",models.DecimalField(decimal_places=12,max_digits=30)),("size",models.DecimalField(decimal_places=12,max_digits=30)),("trade_id",models.CharField(max_length=255)),("provider_timestamp",models.DateTimeField()),("received_at",models.DateTimeField()),("provider_id",models.CharField(max_length=64)),("venue",models.CharField(default="UNKNOWN",max_length=64)),("sequence",models.CharField(blank=True,max_length=128)),("conditions",models.JSONField(default=list)),("provenance",models.JSONField(default=dict))], options={"indexes":[models.Index(fields=["instrument_id","-provider_timestamp"],name="canonical_trade_latest_idx")],"constraints":[models.UniqueConstraint(fields=("provider_id","instrument_id","trade_id"),name="canonical_trade_identity")]}),
        migrations.CreateModel(name="CanonicalMarketStatus", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("instrument_id",models.CharField(max_length=64)),("status",models.CharField(max_length=16)),("halt_status_available",models.BooleanField(default=False)),("provider_timestamp",models.DateTimeField()),("received_at",models.DateTimeField()),("provider_id",models.CharField(max_length=64)),("provenance",models.JSONField(default=dict))], options={"indexes":[models.Index(fields=["instrument_id","-provider_timestamp"],name="canonical_status_latest_idx")]})
    ]
