# Generated by Django 5.2.16 on 2026-08-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=64, unique=True)),
                ('provider_type', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_governance_providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderGovernanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=16)),
                ('reason_code', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider_governance.providerdefinition')),
            ],
            options={
                'db_table': 'provider_governance_audit',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('license_reference', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='provider_governance.providerdefinition')),
            ],
            options={
                'db_table': 'provider_governance_licenses',
            },
        ),
        migrations.CreateModel(
            name='ProviderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(max_length=32)),
                ('environment', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reference', models.CharField(max_length=255, unique=True)),
                ('license_reference', models.CharField(max_length=255)),
                ('credential_reference', models.CharField(max_length=255)),
                ('allowed_products', models.JSONField(default=list)),
                ('allowed_symbols', models.JSONField(default=list)),
                ('allowed_regions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='provider_governance.providerdefinition')),
            ],
            options={
                'db_table': 'provider_governance_provider_approvals',
                'indexes': [models.Index(fields=['provider', 'environment', 'status'], name='provider_go_provide_38c0bb_idx')],
            },
        ),
    ]
