# Generated by Django 5.2.16 on 2026-08-06 21:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


PROVIDER_GOVERNANCE_GUARD_SQL = """
CREATE FUNCTION provider_governance_guard_approval() RETURNS trigger AS $$
DECLARE current_id bigint; current_version integer; declared_type varchar; license_ok boolean;
BEGIN
  IF TG_OP IN ('UPDATE','DELETE') AND OLD.status = 'APPROVED' THEN
    RAISE EXCEPTION 'approved provider approvals are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  SELECT provider_type INTO declared_type FROM provider_governance_providers WHERE id = NEW.provider_id;
  IF declared_type IS NULL OR declared_type <> NEW.provider_type THEN RAISE EXCEPTION 'provider type mismatch'; END IF;
  IF NEW.status = 'APPROVED' THEN
    SELECT EXISTS(SELECT 1 FROM provider_governance_licenses l WHERE l.id=NEW.license_id AND l.provider_id=NEW.provider_id AND l.environment=NEW.environment AND l.status='APPROVED' AND (l.expires_at IS NULL OR l.expires_at > now())) INTO license_ok;
    IF NOT license_ok THEN RAISE EXCEPTION 'approved license required'; END IF;
    SELECT a.id,a.version INTO current_id,current_version FROM provider_governance_provider_approvals a
      WHERE a.provider_id=NEW.provider_id AND a.environment=NEW.environment AND a.status='APPROVED'
        AND NOT EXISTS(SELECT 1 FROM provider_governance_provider_approvals r WHERE r.supersedes_approval_id=a.id)
      LIMIT 1;
    IF current_id IS NOT NULL AND (NEW.supersedes_approval_id IS DISTINCT FROM current_id OR NEW.version <> current_version + 1) THEN
      RAISE EXCEPTION 'approved replacement must supersede current version';
    END IF;
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;
CREATE TRIGGER provider_governance_approval_guard BEFORE INSERT OR UPDATE OR DELETE ON provider_governance_provider_approvals FOR EACH ROW EXECUTE FUNCTION provider_governance_guard_approval();
CREATE FUNCTION provider_governance_guard_audit() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'provider governance audit is append-only'; END $$ LANGUAGE plpgsql;
CREATE TRIGGER provider_governance_audit_guard BEFORE UPDATE OR DELETE ON provider_governance_audit FOR EACH ROW EXECUTE FUNCTION provider_governance_guard_audit();
"""

PROVIDER_GOVERNANCE_GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS provider_governance_audit_guard ON provider_governance_audit;
DROP FUNCTION IF EXISTS provider_governance_guard_audit();
DROP TRIGGER IF EXISTS provider_governance_approval_guard ON provider_governance_provider_approvals;
DROP FUNCTION IF EXISTS provider_governance_guard_approval();
"""


def install_provider_governance_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROVIDER_GOVERNANCE_GUARD_SQL)


def remove_provider_governance_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(PROVIDER_GOVERNANCE_GUARD_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('provider_governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providergovernanceaudit',
            options={'ordering': ['-resolved_at']},
        ),
        migrations.RemoveField(
            model_name='providerapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='providerapproval',
            name='license_reference',
        ),
        migrations.RemoveField(
            model_name='providerapproval',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='providergovernanceaudit',
            name='occurred_at',
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='approval_payload_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='approved_by_principal_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='created_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='credential_policy',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('NONE', 'None')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='provider_governance.providerlicense'),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='supersedes_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='provider_governance.providerapproval'),
        ),
        migrations.AddField(
            model_name='providerapproval',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider_governance.providerapproval'),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='approval_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='audit_event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='caller_service',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='credential_reference_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='credential_reference_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='environment',
            field=models.CharField(default='STAGING', max_length=16),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider_governance.providerlicense'),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='provider_id_evidence',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='provider_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='request_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='requested_product',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='requested_region',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='requested_symbol',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providergovernanceaudit',
            name='resolved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='providerapproval',
            name='credential_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='providerapproval',
            name='environment',
            field=models.CharField(choices=[('STAGING', 'Staging'), ('PRODUCTION', 'Production')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='providerapproval',
            constraint=models.UniqueConstraint(fields=('provider', 'environment', 'version'), name='provider_approval_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='providerapproval',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', ['STAGING', 'PRODUCTION'])), name='provider_approval_environment_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerapproval',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('approved_at')), _connector='OR'), name='provider_approval_expiry_after_approval'),
        ),
        migrations.AddConstraint(
            model_name='providerapproval',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_at__isnull', False), models.Q(('approved_by_principal_id', ''), _negated=True), ('license__isnull', False)), _connector='OR'), name='approved_requires_evidence'),
        ),
        migrations.AddConstraint(
            model_name='providerapproval',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credential_policy', 'NONE'), ('credential_reference__isnull', True)), models.Q(('credential_policy', 'REQUIRED'), ('credential_reference__isnull', False)), _connector='OR'), name='credential_policy_satisfied'),
        ),
        migrations.RunPython(install_provider_governance_guards, remove_provider_governance_guards),
    ]
