from django.urls import path

from .views import (
    RealWalletBalanceListView,
    RealWalletAssetNetworksView,
    RealWalletAssetsView,
    RealWalletDetailView,
    RealWalletDisabledView,
    RealWalletListView,
    RealWalletFeaturesView,
    RealWalletNetworksView,
    DepositListView,
    WalletAddressesView,
    WithdrawalListView,
    RealWalletStatusView,
    WebhookSubscriptionListCreateView,
    WebhookSubscriptionRotateSecretView,
    AdminWithdrawalApprovalView,
    AdminWithdrawalRejectView,
    AdminReconciliationView,
)

app_name = "real_wallet"
disabled = RealWalletDisabledView.as_view()

urlpatterns = [
    path("status/", RealWalletStatusView.as_view(), name="status"),
    path("features/", RealWalletFeaturesView.as_view(), name="features"),
    path("assets/", RealWalletAssetsView.as_view(), name="assets"),
    path("networks/", RealWalletNetworksView.as_view(), name="networks"),
    path("asset-networks/", RealWalletAssetNetworksView.as_view(), name="asset-networks"),
    path("wallets/", RealWalletListView.as_view(), name="wallets"),
    # The canonical public identifier is an asset code. UUID wallet IDs remain
    # accepted by the view for compatibility once reads are authorized.
    path("wallets/<str:wallet_id>/", RealWalletDetailView.as_view(), name="wallet-detail"),
    path("wallets/<uuid:wallet_id>/balances/", RealWalletBalanceListView.as_view(), name="wallet-balances"),
    path("wallets/<uuid:wallet_id>/addresses/", WalletAddressesView.as_view(), name="wallet-addresses"),
    path("wallets/<uuid:wallet_id>/addresses/<uuid:address_id>/", disabled, name="wallet-address-detail"),
    path("wallets/<uuid:wallet_id>/addresses/allocate/", disabled, name="wallet-address-allocate"),
    path("deposits/", DepositListView.as_view(), name="deposits"),
    path("deposits/<uuid:deposit_id>/", disabled, name="deposit-detail"),
    path("deposits/<uuid:deposit_id>/confirmations/", disabled, name="deposit-confirmations"),
    path("deposits/<uuid:deposit_id>/ledger-transaction/", disabled, name="deposit-ledger-transaction"),
    path("deposits/<uuid:deposit_id>/support-review/", disabled, name="deposit-support-review"),
    path("withdrawals/", WithdrawalListView.as_view(), name="withdrawals"),
    path("withdrawals/quote/", disabled, name="withdrawal-quote"),
    path("withdrawals/preview/", disabled, name="withdrawal-preview"),
    path("withdrawals/<uuid:withdrawal_id>/", disabled, name="withdrawal-detail"),
    path("withdrawals/<uuid:withdrawal_id>/confirm/", disabled, name="withdrawal-confirm"),
    path("withdrawals/<uuid:withdrawal_id>/cancel/", disabled, name="withdrawal-cancel"),
    path("withdrawals/<uuid:withdrawal_id>/approvals/", disabled, name="withdrawal-approvals"),
    path("withdrawals/<uuid:withdrawal_id>/blockchain-transaction/", disabled, name="withdrawal-blockchain-transaction"),
    path("transfers/", disabled, name="transfers"),
    path("transfers/preview/", disabled, name="transfer-preview"),
    path("transfers/<uuid:transfer_id>/", disabled, name="transfer-detail"),
    path("transfers/<uuid:transfer_id>/cancel/", disabled, name="transfer-cancel"),
    path("wallet-statements/", disabled, name="wallet-statements"),
    path("wallet-statements/<uuid:statement_id>/", disabled, name="wallet-statement-detail"),
    path("compliance/profile/", disabled, name="compliance-profile"),
    path("compliance/kyc/sessions/", disabled, name="compliance-kyc-sessions"),
    path("compliance/requirements/", disabled, name="compliance-requirements"),
    path("compliance/restrictions/", disabled, name="compliance-restrictions"),
    path("beneficiaries/", disabled, name="beneficiaries"),
    path("api-keys/", disabled, name="api-keys"),
    path("trading/orders/", disabled, name="trading-orders"),
    path("trading/accounts/", disabled, name="trading-accounts"),
    path("notifications/", disabled, name="notifications"),
    path("reports/", disabled, name="reports"),
    path("integrations/webhooks/<str:provider>/<uuid:connection_id>/", disabled, name="provider-webhook"),
    path("webhook-subscriptions/", WebhookSubscriptionListCreateView.as_view(), name="webhook-subscriptions"),
    path("webhook-subscriptions/<uuid:subscription_id>/rotate-secret/", WebhookSubscriptionRotateSecretView.as_view(), name="webhook-subscription-rotate-secret"),
    path("admin/withdrawals/<uuid:withdrawal_id>/approve/", AdminWithdrawalApprovalView.as_view(), name="admin-withdrawal-approve"),
    path("admin/withdrawals/<uuid:withdrawal_id>/reject/", AdminWithdrawalRejectView.as_view(), name="admin-withdrawal-reject"),
    path("admin/reconciliations/", AdminReconciliationView.as_view(), name="admin-reconciliations"),
]
