# Generated by Django 5.0.2 on 2025-01-13 15:05

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[a-zA-Z ]+$')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[a-zA-Z ]+$')])),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{9,15}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_profile_pictures', validators=[users.models.validate_file_size])),
                ('blured_email', models.CharField(blank=True, max_length=255, null=True)),
                ('blured_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=500, null=True)),
                ('two_factor_authentication_enabled', models.BooleanField(default=False)),
                ('hidden_account_balances_toggle_enabled', models.BooleanField(default=False)),
                ('one_click_trade_toggle_enabled', models.BooleanField(default=False)),
                ('one_click_trade_closing_toggle_enabled', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_iso_code', models.CharField(blank=True, max_length=5, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('is_mfa_enabled', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('trader_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_walkthrough', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Super Admin', 'Super Admin')], default='User', max_length=11)),
                ('ip_restricted', models.BooleanField(default=False)),
                ('two_fa_type', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('AUTHENTICATOR_APP', 'AUTHENTICATOR APP')], max_length=100, null=True)),
                ('password_complexity', models.CharField(blank=True, choices=[('SPECIAL_CHARACTERS', 'Special Characters'), ('UPPERCASE_LOWERCASE', 'Uppercase and Lowercase'), ('NUMBERS_AND_SPECIAL_CHARACTERS', 'Numbers and Special Characters'), ('CUSTOM', 'Custom')], max_length=100, null=True)),
                ('custom_characters', models.CharField(blank=True, help_text="Enter password custom characters like @%^$ if 'Custom' is selected.", max_length=255, null=True)),
                ('password_strength', models.CharField(choices=[('STRONG', 'STRONG'), ('MODERATE', 'MODERATE'), ('WEAK', 'WEAK')], default='MODERATE', max_length=64)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('password_max_length', models.PositiveIntegerField(default=20)),
                ('document_verification', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='PENDING', max_length=100)),
                ('face_verification', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='PENDING', max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='PENDING', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Where we got the contact from.', max_length=120, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('driver_license', 'Driver License')], max_length=50)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='P', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='kyc', validators=[users.models.validate_file_size])),
                ('desc', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=2)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.kyc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('failed_checks', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
