# Generated by Django 5.0.2 on 2024-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_walkthrough",
            field=models.BooleanField(default=True),
        ),
    ]
