# Generated by Django 5.0.2 on 2024-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_walkthrough"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_walkthrough",
            field=models.BooleanField(default=False),
        ),
    ]
