# Generated by Django 5.0.2 on 2024-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_walkthrough"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trader_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
