# Generated by Django 5.0.2 on 2024-08-14 03:55

import fx_utils.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_trader_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trader_id",
            field=models.BigIntegerField(
                blank=True, default=fx_utils.generators.generate_trader_id, editable=False, null=True, unique=True
            ),
        ),
    ]
