# Generated by Django 5.0.2 on 2024-08-16 03:32

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("address", models.CharField(max_length=100)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("id_card", "ID Card"),
                            ("driver_license", "Driver License"),
                        ],
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(max_length=100, unique=True)),
                ("selfie", models.ImageField(upload_to="kyc", validators=[users.models.validate_file_size])),
                (
                    "status",
                    models.CharField(choices=[("P", "PENDING"), ("S", "SUCCESSFUL"), ("F", "FAILED")], max_length=2),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KYCFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="kyc", validators=[users.models.validate_file_size])),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="users.kyc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
