# Generated by Django 5.0.2 on 2024-08-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_birthdate_kyc_kycfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycfile",
            name="kyc",
        ),
        migrations.AddField(
            model_name="kyc",
            name="files",
            field=models.ManyToManyField(related_name="files", to="users.kycfile"),
        ),
        migrations.AddField(
            model_name="kycfile",
            name="desc",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kyc",
            name="status",
            field=models.CharField(
                choices=[("P", "PENDING"), ("S", "SUCCESSFUL"), ("F", "FAILED")], default="P", max_length=2
            ),
        ),
    ]
