# Generated by Django 5.0.2 on 2024-08-16 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_kycfile_kyc_kyc_files_kycfile_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kyc",
            name="files",
        ),
        migrations.AddField(
            model_name="kycfile",
            name="kyc",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="files", to="users.kyc"
            ),
            preserve_default=False,
        ),
    ]
