# Generated by Django 5.0.2 on 2024-08-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_kyc_files_kycfile_kyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(choices=[("A", "Admin"), ("U", "User")], default="U", max_length=1),
        ),
    ]
