# Generated by Django 5.0.2 on 2024-08-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_banned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_banned",
        ),
    ]
