# Generated by Django 5.0.2 on 2024-08-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userdeviceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='selfie',
        ),
    ]
