# Generated by Django 5.0.2 on 2024-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_kyc_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('S', 'Super Admin')], default='U', max_length=1),
        ),
    ]
