# Generated by Django 5.0.2 on 2024-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Super Admin', 'Super Admin')], default='User', max_length=11),
        ),
    ]
