# Generated by Django 5.0.2 on 2024-08-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
