# Generated by Django 5.0.2 on 2024-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycfile',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=2),
        ),
    ]
