# Generated by Django 5.0.2 on 2024-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_kycfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_characters',
            field=models.CharField(blank=True, help_text="Enter password custom characters like @%^$ if 'Custom' is selected.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_complexity',
            field=models.CharField(choices=[('', ''), ('SPECIAL_CHARACTERS', 'Special Characters'), ('UPPERCASE_LOWERCASE', 'Uppercase and Lowercase'), ('NUMBERS_AND_SPECIAL_CHARACTERS', 'Numbers and Special Characters'), ('CUSTOM', 'Custom')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password_max_length',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password_min_length',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='user',
            name='password_strength',
            field=models.CharField(choices=[('', ''), ('STRONG', 'STRONG'), ('MODERATE', 'MODERATE'), ('WEAK', 'WEAK')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_type',
            field=models.CharField(choices=[('', ''), ('SMS', 'SMS'), ('AUTHENTICATOR_APP', 'AUTHENTICATOR APP')], default='', max_length=100),
        ),
    ]
