# Generated by Django 5.0.2 on 2024-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_custom_characters_user_ip_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_verification',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='face_verification',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='', max_length=100),
        ),
    ]
