# Generated by Django 5.0.2 on 2024-09-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_document_verification_user_face_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.CharField(blank=True, help_text='Where we got the contact from.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_verification',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_verification',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('', ''), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CHANGE_PASSWORD', 'Change Password')], default='', max_length=100),
        ),
    ]
