# Generated by Django 5.0.2 on 2025-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_brand_alter_user_document_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
