# Generated by Django 5.0.2 on 2025-01-18 15:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_user_preferred_language"),
    ]
    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("User", "User"), ("Admin", "Admin"), ("Super_Admin", "Super Admin")],
                default="User",
                max_length=11,
            ),
        ),
    ]
