# Generated by Django 5.0.2 on 2025-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
            ],
        ),
    ]
