# Generated by Django 5.0.2 on 2025-01-18 15:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_user_preferred_language"),
    ]
    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("User", "User"), ("Admin", "Admin"), ("Super_Admin", "Super Admin")],
                default="User",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_zone", models.CharField(default="UTC", max_length=100)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=50)),
            ],
        ),
    ]
