# Generated by Django 5.0.2 on 2025-01-20 12:56
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_user_role_adminsettings"),
    ]
    operations = [
        migrations.AlterField(
            model_name="user",
            name="two_fa_type",
            field=models.CharField(
                choices=[("NOT_SET", ""), ("SMS", "SMS"), ("AUTHENTICATOR_APP", "AUTHENTICATOR APP")],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
