# Generated by Django 5.0.2 on 2025-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
