# Generated by Django 5.0.2 on 2025-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_user_time_zone_alter_user_two_fa_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
