# Generated by Codex on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_keycloak_identity_binding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("User", "User"),
                    ("Contractor", "Contractor"),
                    ("Admin", "Admin"),
                    ("Super_Admin", "Super Admin"),
                ],
                default="User",
                max_length=11,
            ),
        ),
    ]
