# Generated by Django 5.0.2 on 2025-01-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
