# Generated by Django 5.0.2 on 2025-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_supportticket_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
