# Generated by Django 5.0.2 on 2025-01-25 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_supportticket_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
