# Generated by Django 5.0.2 on 2025-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_supportticket_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
