# Generated by Django 5.0.2 on 2025-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_supportticket_assigned_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In_Progress", "In Progress"),
                    ("Escalated", "Escalated"),
                    ("Resolved", "Resolved"),
                    ("Cancelled", "Cancelled"),
                    ("Reopened", "Reopened"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
