# Generated by Django 5.0.2 on 2024-08-21 20:20

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('bank', 'bank'), ('epayment', 'epayment'), ('crypto', 'crypto')])),
                ('icon', models.FileField(blank=True, null=True, upload_to=payments.models.upload, validators=[payments.models.validate_file_size])),
                ('account_id', models.CharField(max_length=100)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
