# Generated by Django 5.0.2 on 2025-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsprovider_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('bank', 'bank'), ('epayment', 'epayment'), ('crypto', 'crypto')], max_length=50),
        ),
    ]
