# Generated by Django 5.0.2 on 2025-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_type_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='network',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_details',
            field=models.JSONField(blank=True, default=dict, help_text='Store payment-specific details'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('crypto', 'Cryptocurrency'), ('e_wallet', 'E-Wallet')], max_length=50),
        ),
    ]
