from django.urls import path

from trade.demo_engine import DemoTradeListView, DemoWalletRefillView
from users.views import PasswordResetRequestView, VerifyMFAView

from . import api


urlpatterns = [
    path("auth/login", api.CanonicalLoginView.as_view()),
    path("auth/logout", api.CanonicalLogoutView.as_view()),
    path("auth/password/forgot", PasswordResetRequestView.as_view()),
    path("auth/password/reset", api.PasswordResetView.as_view()),
    path("auth/mfa/setup", api.MfaSetupView.as_view()),
    path("auth/mfa/verify", VerifyMFAView.as_view()),
    path("auth/mfa/disable", api.MfaDisableView.as_view()),
    path("me", api.MeView.as_view()),
    path("account", api.AccountView.as_view()),
    path("account/sessions", api.AccountSessionCollectionView.as_view()),
    path("account/sessions/<uuid:session_id>", api.AccountSessionDetailView.as_view()),
    path("account/security-events", api.AccountSecurityEventView.as_view()),
    path("compliance/restrictions", api.ComplianceRestrictionView.as_view()),
    path("demo/account", api.DemoAccountView.as_view()),
    path("demo/wallets", api.DemoWalletsView.as_view()),
    path("demo/wallets/refill", DemoWalletRefillView.as_view()),
    path("demo/orders", api.DemoOrderCollectionView.as_view()),
    path("demo/trades", DemoTradeListView.as_view()),
    path("demo/positions", api.DemoPositionsView.as_view()),
    path("wallets", api.FeatureDisabledView.as_view()),
    path("wallets/<str:asset>", api.FeatureDisabledView.as_view()),
    path("deposits", api.FeatureDisabledView.as_view()),
    path("deposits/<uuid:resource_id>", api.FeatureDisabledView.as_view()),
    path("withdrawals", api.FeatureDisabledView.as_view()),
    path("withdrawals/preview", api.FeatureDisabledView.as_view()),
    path("withdrawals/<uuid:resource_id>", api.FeatureDisabledView.as_view()),
    path("withdrawals/<uuid:resource_id>/cancel", api.FeatureDisabledView.as_view()),
    path("transfers", api.FeatureDisabledView.as_view()),
    path("transfers/preview", api.FeatureDisabledView.as_view()),
    path("transfers/<uuid:resource_id>", api.FeatureDisabledView.as_view()),
    path("notifications", api.NotificationCollectionView.as_view()),
    path("notifications/<uuid:notification_id>/read", api.NotificationReadView.as_view()),
    path("notifications/read-all", api.NotificationReadAllView.as_view()),
    path("notifications/preferences", api.NotificationPreferenceView.as_view()),
    path("support/cases", api.SupportCaseCollectionView.as_view()),
    path("support/cases/<uuid:case_id>", api.SupportCaseDetailView.as_view()),
    path("support/cases/<uuid:case_id>/messages", api.SupportMessageView.as_view()),
    path("reports/exports", api.ReportExportCollectionView.as_view()),
    path("reports/exports/<uuid:export_id>", api.ReportExportDetailView.as_view()),
    path("reports/<str:report_type>", api.ReportView.as_view()),
    path("privacy/exports", api.PrivacyExportView.as_view()),
    path("privacy/exports/<uuid:request_id>", api.PrivacyRequestDetailView.as_view()),
    path("privacy/deletion-requests", api.PrivacyDeletionView.as_view()),
    path("privacy/requests", api.PrivacyRequestCollectionView.as_view()),
    path("operator/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/actions/<uuid:action_id>/approve", api.OperatorActionApproveView.as_view()),
    path("operator/accounts/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/support/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/security/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/compliance/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/incidents/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/providers/actions", api.OperatorActionCollectionView.as_view()),
    path("operator/audit", api.OperatorActionCollectionView.as_view()),
    path("status", api.StatusView.as_view()),
    path("features", api.FeatureView.as_view()),
    path("webhooks/<str:provider>/<str:purpose>", api.ProviderWebhookView.as_view()),
]
