# Generated by Django 5.2.16 on 2026-08-11 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref', models.CharField(max_length=128)),
                ('actor_ref', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_ref', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_ref', 'resource_type', 'resource_ref', 'occurred_at'], name='surv_audit_resource_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('tenant_ref', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('failure_category', models.CharField(max_length=64)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField()),
                ('last_failed_at', models.DateTimeField()),
                ('safe_error_ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_id', 'event_type'), name='surveillance_dead_letter_unique')],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('SELF_TRADE_ATTEMPT', 'SELF_TRADE_ATTEMPT'), ('WASH_TRADE_PATTERN', 'WASH_TRADE_PATTERN'), ('SPOOFING_INDICATOR', 'SPOOFING_INDICATOR'), ('LAYERING_INDICATOR', 'LAYERING_INDICATOR'), ('EXCESSIVE_CANCEL_PATTERN', 'EXCESSIVE_CANCEL_PATTERN'), ('RAPID_ORDER_FLIP', 'RAPID_ORDER_FLIP'), ('MARKET_CLOSE_ORDER_PATTERN', 'MARKET_CLOSE_ORDER_PATTERN'), ('RESTRICTED_INSTRUMENT_ATTEMPT', 'RESTRICTED_INSTRUMENT_ATTEMPT'), ('ACCOUNT_RESTRICTION_VIOLATION', 'ACCOUNT_RESTRICTION_VIOLATION'), ('PRICE_DEVIATION_ORDER', 'PRICE_DEVIATION_ORDER'), ('VOLUME_ANOMALY_ORDER', 'VOLUME_ANOMALY_ORDER'), ('ORDER_RATE_ANOMALY', 'ORDER_RATE_ANOMALY'), ('CROSS_ACCOUNT_COORDINATION_INDICATOR', 'CROSS_ACCOUNT_COORDINATION_INDICATOR'), ('SUSPICIOUS_POSITION_BUILDUP', 'SUSPICIOUS_POSITION_BUILDUP'), ('OTHER_REVIEW_REQUIRED', 'OTHER_REVIEW_REQUIRED')], max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=16)),
                ('asset_class', models.CharField(default='ALL', max_length=32)),
                ('parameters_json_safe', models.JSONField(default=dict)),
                ('policy_version', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'effective_from'], name='surv_rule_effective_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='surveillance_rule_version_unique'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('name',), name='surveillance_one_current_rule')],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref', models.CharField(max_length=128)),
                ('account_ref', models.CharField(max_length=128)),
                ('instrument_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('SELF_TRADE_ATTEMPT', 'SELF_TRADE_ATTEMPT'), ('WASH_TRADE_PATTERN', 'WASH_TRADE_PATTERN'), ('SPOOFING_INDICATOR', 'SPOOFING_INDICATOR'), ('LAYERING_INDICATOR', 'LAYERING_INDICATOR'), ('EXCESSIVE_CANCEL_PATTERN', 'EXCESSIVE_CANCEL_PATTERN'), ('RAPID_ORDER_FLIP', 'RAPID_ORDER_FLIP'), ('MARKET_CLOSE_ORDER_PATTERN', 'MARKET_CLOSE_ORDER_PATTERN'), ('RESTRICTED_INSTRUMENT_ATTEMPT', 'RESTRICTED_INSTRUMENT_ATTEMPT'), ('ACCOUNT_RESTRICTION_VIOLATION', 'ACCOUNT_RESTRICTION_VIOLATION'), ('PRICE_DEVIATION_ORDER', 'PRICE_DEVIATION_ORDER'), ('VOLUME_ANOMALY_ORDER', 'VOLUME_ANOMALY_ORDER'), ('ORDER_RATE_ANOMALY', 'ORDER_RATE_ANOMALY'), ('CROSS_ACCOUNT_COORDINATION_INDICATOR', 'CROSS_ACCOUNT_COORDINATION_INDICATOR'), ('SUSPICIOUS_POSITION_BUILDUP', 'SUSPICIOUS_POSITION_BUILDUP'), ('OTHER_REVIEW_REQUIRED', 'OTHER_REVIEW_REQUIRED')], max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('detected_at', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('rule_version', models.PositiveIntegerField()),
                ('policy_version', models.CharField(max_length=32)),
                ('score', models.DecimalField(decimal_places=5, max_digits=8)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('REVIEWING', 'REVIEWING'), ('ESCALATED', 'ESCALATED'), ('RESOLVED', 'RESOLVED'), ('DISMISSED', 'DISMISSED')], default='OPEN', max_length=16)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('evidence_safe', models.JSONField(default=dict)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveillance.surveillancerule')),
            ],
        ),
        migrations.CreateModel(
            name='TradingRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref', models.CharField(max_length=128)),
                ('scope_type', models.CharField(choices=[('ACCOUNT', 'ACCOUNT'), ('TENANT', 'TENANT'), ('INSTRUMENT', 'INSTRUMENT'), ('ASSET_CLASS', 'ASSET_CLASS'), ('VENUE', 'VENUE'), ('JURISDICTION', 'JURISDICTION')], max_length=16)),
                ('scope_ref', models.CharField(max_length=128)),
                ('restriction_type', models.CharField(choices=[('BLOCK_NEW_ORDERS', 'BLOCK_NEW_ORDERS'), ('CANCEL_ONLY', 'CANCEL_ONLY'), ('CLOSE_ONLY', 'CLOSE_ONLY'), ('BLOCK_BUYS', 'BLOCK_BUYS'), ('BLOCK_SELLS', 'BLOCK_SELLS'), ('BLOCK_INSTRUMENT', 'BLOCK_INSTRUMENT'), ('BLOCK_ASSET_CLASS', 'BLOCK_ASSET_CLASS'), ('BLOCK_VENUE', 'BLOCK_VENUE'), ('REVIEW_REQUIRED', 'REVIEW_REQUIRED')], max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('REMOVED', 'REMOVED'), ('EXPIRED', 'EXPIRED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_ref', 'scope_type', 'scope_ref', 'status'], name='surv_restriction_scope_idx'), models.Index(fields=['effective_from', 'effective_to'], name='surv_restriction_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref', models.CharField(max_length=128)),
                ('account_ref', models.CharField(max_length=128)),
                ('case_type', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_REVIEW', 'IN_REVIEW'), ('ESCALATED', 'ESCALATED'), ('RESTRICTED', 'RESTRICTED'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=16)),
                ('assigned_to', models.CharField(blank=True, max_length=128)),
                ('opened_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=64)),
                ('policy_version', models.CharField(max_length=32)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('events', models.ManyToManyField(related_name='cases', to='surveillance.surveillanceevent')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_ref', 'status', 'opened_at'], name='surv_case_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='surveillanceevent',
            index=models.Index(fields=['tenant_ref', 'account_ref', 'detected_at'], name='surv_event_account_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceevent',
            index=models.Index(fields=['instrument_id', 'event_type', 'detected_at'], name='surv_event_instrument_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceevent',
            index=models.Index(fields=['status', 'severity', 'detected_at'], name='surv_event_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveillanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_id__isnull', False)), fields=('source_event_id', 'rule'), name='surveillance_source_rule_unique'),
        ),
    ]
