# Generated by Django 5.2.16 on 2026-08-11 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_seed_rules_and_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceCaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CASE_OPENED', 'CASE_OPENED'), ('CASE_ASSIGNED', 'CASE_ASSIGNED'), ('CASE_ESCALATED', 'CASE_ESCALATED'), ('CASE_RESOLVED', 'CASE_RESOLVED'), ('CASE_CLOSED', 'CASE_CLOSED'), ('NOTE_ADDED', 'NOTE_ADDED')], max_length=32)),
                ('actor_ref', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='surveillance.surveillancecase')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'occurred_at'], name='surv_case_timeline_idx')],
            },
        ),
    ]
