from abc import ABC, abstractmethod


class ExecutionProvider(ABC):
    @abstractmethod
    def submit_order(self, order): ...
    @abstractmethod
    def cancel_order(self, provider_order_id): ...
    @abstractmethod
    def get_order(self, provider_order_id): ...
    @abstractmethod
    def get_positions(self, account_ref): ...
    @abstractmethod
    def health(self): ...
