from abc import ABC, abstractmethod


class ExecutionProvider(ABC):
    @abstractmethod
    def capabilities(self): ...
    @abstractmethod
    def preview_order(self, order): ...
    @abstractmethod
    def submit_order(self, order): ...
    @abstractmethod
    def cancel_order(self, provider_order_id): ...
    @abstractmethod
    def replace_order(self, provider_order_id, changes): ...
    @abstractmethod
    def get_order(self, provider_order_id): ...
    @abstractmethod
    def list_orders(self, account_ref): ...
    @abstractmethod
    def get_executions(self, provider_order_id): ...
    @abstractmethod
    def resolve_unknown_operation(self, client_order_id): ...
    @abstractmethod
    def health(self): ...
