from rest_framework.response import Response


MESSAGES = {
    "FEATURE_DISABLED": "This feature is not enabled.",
    "RESOURCE_NOT_FOUND": "The requested resource was not found.",
    "IDEMPOTENCY_CONFLICT": "The idempotency key was used with a different request.",
    "TRADING_HALTED": "Trading is halted for this scope.",
    "MARKET_DATA_STALE": "Current market data is temporarily unavailable.",
    "PRICE_STALE": "A current market price is unavailable.",
    "PRICE_UNAVAILABLE": "A current market price is unavailable.",
    "PRICE_INVALID": "The current market price is invalid.",
    "PROVIDER_UNAVAILABLE": "The canonical price provider is unavailable.",
    "MARKET_CLOSED": "The market is closed.",
    "INSUFFICIENT_AVAILABLE_BALANCE": "The simulated available balance is insufficient.",
    "INSUFFICIENT_AVAILABLE_POSITION": "The simulated available position is insufficient.",
    "ORDER_INVALID_STATE": "This simulated order can no longer be changed.",
    "VALIDATION_ERROR": "Some order information needs to be corrected.",
    "SIMULATION_AUTHORITY_REQUIRED": "Simulation authority is required.",
    "TRADING_NOT_AVAILABLE": "Trading is not available for this account or instrument.",
    "ORDER_REJECTED": "The order could not be accepted.",
    "ACCOUNT_REVIEW_REQUIRED": "Your account is being reviewed.",
    "SURVEILLANCE_TEMPORARILY_UNAVAILABLE": "Trading controls are temporarily unavailable.",
    "PERMISSION_DENIED": "You do not have permission to perform this action.",
    "SELF_APPROVAL_FORBIDDEN": "Independent approval is required.",
    "TRADE_NOT_FOUND": "The trade could not be found.",
    "SETTLEMENT_NOT_FOUND": "The settlement record could not be found.",
    "POST_TRADE_EXCEPTION": "This trade requires review.",
    "SETTLEMENT_PENDING": "Settlement is pending.",
    "SETTLEMENT_UNAVAILABLE": "Settlement information is temporarily unavailable.",
    "INSTRUMENT_REQUIRED": "An instrument is required.",
    "INSTRUMENT_UNAVAILABLE": "The instrument is not active in the canonical reference-data authority.",
    "INSTRUMENT_AMBIGUOUS": "The symbol identifies more than one active instrument; use its canonical UUID.",
    "INSTRUMENT_RULES_UNAVAILABLE": "Authoritative instrument rules are unavailable.",
    "FEE_POLICY_UNAVAILABLE": "The authoritative fee policy is unavailable.",
    "TENANT_SELECTION_REQUIRED": "Select an organization using X-Organization-ID.",
    "ORGANIZATION_NOT_AUTHORIZED": "The selected organization is not authorized.",
    "ORGANIZATION_REQUIRED": "An active organization is required.",
    "INVALID_ORGANIZATION": "The organization identifier is invalid.",
    "IDEMPOTENCY_KEY_REQUIRED": "Idempotency-Key is required.",
    "IF_MATCH_REQUIRED": "If-Match is required.",
    "VERSION_CONFLICT": "The resource version is stale.",
    "RESERVATION_INCREASE_REQUIRED": "This replacement would require a larger reservation.",
    "LIMIT_PRICE_REQUIRED": "A LIMIT order requires limit_price.",
    "ORDER_TYPE_UNSUPPORTED": "This order type is not available for PAPER trading.",
    "INVALID_QUANTITY": "Quantity must be a finite positive decimal.",
    "INVALID_PRICE": "Price must be a finite positive decimal.",
    "INVALID_QUANTITY_PRECISION": "Quantity precision is not supported.",
    "INVALID_PRICE_PRECISION": "Price precision is not supported.",
    "INVALID_SIDE": "Order side must be BUY or SELL.",
    "INVALID_LOT_SIZE": "Quantity must conform to the instrument lot size.",
    "INVALID_TICK_SIZE": "Price must conform to the instrument tick size.",
    "MIN_QUANTITY_NOT_MET": "Quantity is below the instrument minimum.",
    "MAX_QUANTITY_EXCEEDED": "Quantity exceeds the instrument maximum.",
    "MIN_NOTIONAL_NOT_MET": "Order notional is below the instrument minimum.",
    "MAX_NOTIONAL_EXCEEDED": "Order notional exceeds the instrument maximum.",
    "MAX_POSITION_EXCEEDED": "The order would exceed the position limit.",
    "DAILY_LIMIT_EXCEEDED": "The order would exceed a daily trading limit.",
    "INSUFFICIENT_FUNDS": "Available funds are insufficient.",
    "INSUFFICIENT_AVAILABLE_POSITION": "Available position is insufficient.",
    "POSITION_NOT_LONG": "Only a positive PAPER position can be reduced or closed.",
    "POSITION_REDUCTION_EXCEEDS_AVAILABLE": "The reduction exceeds the available position.",
    "REPLACE_PRICE_ONLY": "Mission 1 replacement accepts only limit_price.",
    "REPLACE_LIMIT_ONLY": "Only LIMIT orders can be replaced.",
}


def error_response(request, code, status_code, details=None):
    request_id = str(getattr(request, "request_id", "") or request.headers.get("X-Request-ID", ""))
    correlation_id = str(getattr(request, "correlation_id", "") or request.headers.get("X-Correlation-ID", ""))
    return Response({"error": {"code": code, "message": MESSAGES.get(code, "The request could not be completed."), "request_id": request_id, "correlation_id": correlation_id, "details": details or {}}}, status=status_code)
