# Generated by Django 5.2.16 on 2026-08-07 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("news_app", "0001_news_calendar_contracts")]
    operations = [
        migrations.RenameIndex(model_name="economiccalendarevent", new_name="economic_ca_status_21a137_idx", old_name="economic_ca_status_f0be0e_idx"),
        migrations.RenameIndex(model_name="newsarticle", new_name="news_articl_status_bed246_idx", old_name="news_articl_status_f3460a_idx"),
    ]
