# Generated by Django 5.0.2 on 2025-01-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsnotifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
