# Generated by Django 5.2.16 on 2026-08-11 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'Etf'), ('CRYPTO', 'Crypto'), ('FX', 'Fx'), ('FUTURE', 'Future'), ('OPTION', 'Option'), ('BOND', 'Bond'), ('COMMODITY', 'Commodity'), ('INDEX', 'Index')], max_length=16)),
                ('currency', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HALTED', 'Halted'), ('DELISTED', 'Delisted'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=12)),
                ('cusip', models.CharField(blank=True, db_index=True, max_length=9)),
                ('figi', models.CharField(blank=True, db_index=True, max_length=12)),
                ('tick_size', models.DecimalField(decimal_places=12, max_digits=30)),
                ('lot_size', models.DecimalField(decimal_places=12, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('canonical_symbol',),
            },
        ),
        migrations.CreateModel(
            name='ReferenceDataAudit',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_ref', models.CharField(max_length=160)),
                ('actor_ref', models.CharField(default='system', max_length=160)),
                ('occurred_at', models.DateTimeField()),
                ('evidence_hash', models.CharField(max_length=64)),
                ('metadata_safe', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('occurred_at', 'audit_id'),
            },
        ),
        migrations.CreateModel(
            name='TradingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('timezone', models.CharField(max_length=64)),
                ('continuous', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('mic', models.CharField(blank=True, db_index=True, max_length=4)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSymbolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=64)),
                ('provider_symbol', models.CharField(max_length=128)),
                ('product', models.CharField(default='MARKET_DATA', max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_mappings', to='reference_data.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MarketDataObservation',
            fields=[
                ('observation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=64)),
                ('provider_symbol', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_safe', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_observations', to='reference_data.instrument')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='reference_data.marketdataobservation')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_data.providersymbolmapping')),
            ],
            options={
                'ordering': ('instrument_id', 'observed_at', 'recorded_at'),
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='reference_data.tradingcalendar'),
        ),
        migrations.CreateModel(
            name='CalendarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular'), ('EARLY_CLOSE', 'Early Close'), ('CLOSED', 'Closed'), ('AUCTION', 'Auction')], max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reference_data.tradingcalendar')),
            ],
            options={
                'ordering': ('session_date', 'opens_at'),
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='reference_data.venue'),
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SPLIT', 'Split'), ('DIVIDEND', 'Dividend'), ('MERGER', 'Merger'), ('SYMBOL_CHANGE', 'Symbol Change'), ('DELISTING', 'Delisting'), ('TOKEN_MIGRATION', 'Token Migration'), ('FORK', 'Fork'), ('EXPIRY', 'Expiry'), ('ROLL', 'Roll'), ('EXERCISE', 'Exercise'), ('ASSIGNMENT', 'Assignment')], max_length=24)),
                ('announced_at', models.DateTimeField()),
                ('effective_at', models.DateTimeField()),
                ('source_provider', models.CharField(max_length=64)),
                ('source_reference', models.CharField(max_length=160)),
                ('terms', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='reference_data.corporateaction')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions', to='reference_data.instrument')),
            ],
            options={
                'ordering': ('effective_at',),
                'constraints': [models.UniqueConstraint(fields=('source_provider', 'source_reference'), name='reference_corporate_action_source')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HALTED', 'Halted'), ('DELISTED', 'Delisted'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], max_length=16)),
                ('tick_size', models.DecimalField(decimal_places=12, max_digits=30)),
                ('lot_size', models.DecimalField(decimal_places=12, max_digits=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reference_data.instrument')),
            ],
            options={
                'ordering': ('instrument_id', 'effective_from'),
                'constraints': [models.UniqueConstraint(fields=('instrument', 'version'), name='reference_instrument_version')],
            },
        ),
        migrations.CreateModel(
            name='MarketStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREOPEN', 'Preopen'), ('OPEN', 'Open'), ('AUCTION', 'Auction'), ('HALTED', 'Halted'), ('CLOSED', 'Closed'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('effective_at', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('source_provider', models.CharField(max_length=64)),
                ('source_reference', models.CharField(max_length=160)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_status_records', to='reference_data.instrument')),
            ],
            options={
                'ordering': ('instrument_id', '-effective_at'),
                'constraints': [models.UniqueConstraint(fields=('source_provider', 'source_reference'), name='reference_market_status_source')],
            },
        ),
        migrations.AddIndex(
            model_name='providersymbolmapping',
            index=models.Index(fields=['provider_id', 'product', 'provider_symbol', 'effective_from'], name='reference_provider_lookup'),
        ),
        migrations.AddConstraint(
            model_name='providersymbolmapping',
            constraint=models.UniqueConstraint(fields=('provider_id', 'product', 'provider_symbol', 'effective_from'), name='reference_provider_mapping_identity'),
        ),
        migrations.AddConstraint(
            model_name='providersymbolmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('provider_id', 'product', 'provider_symbol'), name='reference_one_current_provider_symbol'),
        ),
        migrations.AddConstraint(
            model_name='marketdataobservation',
            constraint=models.UniqueConstraint(fields=('provider_id', 'data_type', 'provider_event_id'), name='reference_market_observation_source'),
        ),
        migrations.AddConstraint(
            model_name='calendarsession',
            constraint=models.UniqueConstraint(fields=('calendar', 'session_date', 'kind'), name='reference_calendar_session_identity'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('canonical_symbol', 'venue'), name='reference_canonical_symbol_venue'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('venue__isnull', True)), fields=('canonical_symbol',), name='reference_otc_canonical_symbol'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('isin', ''), _negated=True), fields=('isin',), name='reference_unique_isin'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('cusip', ''), _negated=True), fields=('cusip',), name='reference_unique_cusip'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('figi', ''), _negated=True), fields=('figi',), name='reference_unique_figi'),
        ),
        migrations.AddConstraint(
            model_name='instrumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('instrument',), name='reference_one_current_instrument_version'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.CheckConstraint(condition=models.Q(('tick_size__gt', 0)), name='reference_positive_tick_size'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.CheckConstraint(condition=models.Q(('lot_size__gt', 0)), name='reference_positive_lot_size'),
        ),
    ]
