"""
Django settings for FX project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import json
import os
import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

load_dotenv()

API_ENV = os.getenv("API_ENV", os.getenv("API_ENVIRONMENT", "production")).lower()
NUM_PROXIES = int(os.getenv("NUM_PROXIES", "0"))
PAPER_TRADING_ONLY = os.getenv("PAPER_TRADING_ONLY", "true").lower() in {"1", "true", "yes"}
REAL_WALLET_REQUIRE_MFA = os.getenv("REAL_WALLET_REQUIRE_MFA", "true").lower() in {"1", "true", "yes"}
GUEST_DEMO_ENABLED = os.getenv("GUEST_DEMO_ENABLED", "true").lower() in {"1", "true", "yes"}
GUEST_DEMO_TTL_SECONDS = int(os.getenv("GUEST_DEMO_TTL_SECONDS", "1800"))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
EMAIL_REGISTRATION_ENABLED = os.getenv("EMAIL_REGISTRATION_ENABLED", "true").lower() == "true"
EMAIL_OTP_VERIFICATION_ENABLED = os.getenv("EMAIL_OTP_VERIFICATION_ENABLED", "true").lower() == "true"
EMAIL_OTP_LENGTH = 6
EMAIL_OTP_TTL_SECONDS = int(os.getenv("EMAIL_OTP_TTL_SECONDS", "600"))
EMAIL_OTP_MAX_ATTEMPTS = int(os.getenv("EMAIL_OTP_MAX_ATTEMPTS", "5"))
EMAIL_OTP_RESEND_COOLDOWN_SECONDS = int(os.getenv("EMAIL_OTP_RESEND_COOLDOWN_SECONDS", "60"))
EMAIL_OTP_MAX_SENDS_PER_HOUR = int(os.getenv("EMAIL_OTP_MAX_SENDS_PER_HOUR", "5"))
EMAIL_OTP_PEPPER = os.getenv("EMAIL_OTP_PEPPER", SECRET_KEY)
STAGING_TEST_OTP_SECRET = os.getenv("STAGING_TEST_OTP_SECRET", "")
PENDING_REGISTRATION_TTL_SECONDS = int(os.getenv("PENDING_REGISTRATION_TTL_SECONDS", "86400"))
TRANSACTIONAL_EMAIL_ENABLED = os.getenv("TRANSACTIONAL_EMAIL_ENABLED", "false").lower() == "true"
WELCOME_EMAIL_ENABLED = os.getenv("WELCOME_EMAIL_ENABLED", "false").lower() == "true"
GOOGLE_AUTH_ENABLED = os.getenv("GOOGLE_AUTH_ENABLED", "false").lower() == "true"
GOOGLE_OIDC_CLIENT_ID = os.getenv("GOOGLE_OIDC_CLIENT_ID", "")
GOOGLE_OIDC_CLIENT_SECRET = os.getenv("GOOGLE_OIDC_CLIENT_SECRET", "")
GOOGLE_OIDC_REDIRECT_URI = os.getenv("GOOGLE_OIDC_REDIRECT_URI", "")
GOOGLE_OIDC_SCOPES = os.getenv("GOOGLE_OIDC_SCOPES", "openid email profile")
REALTIME_V2_ENABLED = os.getenv("REALTIME_V2_ENABLED", "false").lower() == "true"
REALTIME_V2_STAGING_ENABLED = os.getenv("REALTIME_V2_STAGING_ENABLED", "false").lower() == "true"
REALTIME_V2_V1_FALLBACK_ENABLED = os.getenv("REALTIME_V2_V1_FALLBACK_ENABLED", "true").lower() == "true"
CENTRIFUGO_ENABLED = os.getenv("CENTRIFUGO_ENABLED", "false").lower() == "true"
NATS_JETSTREAM_ENABLED = os.getenv("NATS_JETSTREAM_ENABLED", "false").lower() == "true"
PRODUCTION_REALTIME_V2_ENABLED = os.getenv("PRODUCTION_REALTIME_V2_ENABLED", "false").lower() == "true"
REAL_MONEY_ENABLED = os.getenv("REAL_MONEY_ENABLED", "false").lower() == "true"
LIVE_TRADING_ENABLED = os.getenv("LIVE_TRADING_ENABLED", "false").lower() == "true"
REAL_TRADING_ENABLED = False
EXTERNAL_EXECUTION_ENABLED = False
REAL_WALLET_READ_ENABLED = False
REAL_DEPOSITS_ENABLED = False
REAL_WITHDRAWALS_ENABLED = False
REAL_INTERNAL_TRANSFERS_ENABLED = False
PAYMENTS_ENABLED = os.getenv("PAYMENTS_ENABLED", "false").lower() == "true"
GOOGLE_OIDC_TRANSACTION_TTL_SECONDS = int(os.getenv("GOOGLE_OIDC_TRANSACTION_TTL_SECONDS", "600"))
AUTH_ALLOWED_RETURN_PATHS = ["/platform", "/platform/trades", "/platform/profile", "/platform/settings"]
LEGAL_SERVICE_AGREEMENT_VERSION = os.getenv("LEGAL_SERVICE_AGREEMENT_VERSION", "demo-v1")
LEGAL_PRIVACY_POLICY_VERSION = os.getenv("LEGAL_PRIVACY_POLICY_VERSION", "demo-v1")
LEGAL_RISK_DISCLOSURE_VERSION = os.getenv("LEGAL_RISK_DISCLOSURE_VERSION", "demo-v1")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = json.loads(os.getenv("ALLOWED_HOSTS"))
CSRF_TRUSTED_ORIGINS = json.loads(os.getenv("CSRF_TRUSTED_ORIGINS"))

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"
CORS_ALLOWED_ORIGINS = json.loads(os.getenv("CORS_ALLOWED_ORIGINS", "[]"))
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "false").lower() == "true"

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

SHORT_UUID_LEN = os.getenv("SHORT_UUID_LEN", 9)

INSTALLED_APPS = [
    "daphne",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "django_prometheus",
    "drf_spectacular",
    "rangefilter",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
    "users",
    "api_trade",
    "wallet",
    "notifications",
    "ws",
    "news_app",
    "trade",
    "tickets",
    "payments",
    "portfolio",
    "bank_account_app",
    "security",
    "coinmarketcharts",
    "django_celery_beat",
    "wsnotifications",
    "reporting",
    "integrations",
    "real_wallet",
    "provider_governance",
    "financial_client",
    "apps.foundation",
    "apps.trading",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "middleware.deprecation.LegacyApiDeprecationMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "middleware.user_login_activity.UserLoginActivityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "middleware.user_preferred_language.UserPreferredLanguageMiddleware",
]
MIDDLEWARE.insert(0, "middleware.correlation.CorrelationIdMiddleware")

ROOT_URLCONF = "FX.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "FX.wsgi.application"

ASGI_APPLICATION = "FX.asgi.application"
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "TEST": {
            # Keep automated tests isolated from the staging database and
            # allow CI to provide its own disposable database name.
            "NAME": os.getenv("TEST_DB_NAME", "test_tradi_staging_ci"),
        },
    }
}

# Private service boundary only. Financial PostgreSQL is intentionally absent
# from DATABASES and its credentials must never be supplied to this process.
FINANCIAL_SERVICE_URL = os.getenv("FINANCIAL_SERVICE_URL", "https://financial-mtls:8443")
FINANCIAL_SERVICE_CLIENT_CERT = os.getenv("FINANCIAL_SERVICE_CLIENT_CERT", "/run/secrets/financial/client.crt")
FINANCIAL_SERVICE_CLIENT_KEY = os.getenv("FINANCIAL_SERVICE_CLIENT_KEY", "/run/secrets/financial/client.key")
FINANCIAL_SERVICE_CA_CERT = os.getenv("FINANCIAL_SERVICE_CA_CERT", "/run/secrets/financial/ca.crt")

# REDIS
REDIS_CACHE_CUSTOM_TIMEOUT = os.getenv("REDIS_CACHE_CUSTOM_TIMEOUT", 30)
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_DATABASE = os.getenv("REDIS_DATABASE")
REDIS_POOL_MAX_CONNECTIONS = os.getenv("REDIS_POOL_MAX_CONNECTIONS")
REDIS_EXPIRE_KEY = os.getenv("REDIS_EXPIRE_KEY")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DATABASE}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}



# CELERY
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = {"application/json"}
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True


CELERY_BEAT_SCHEDULE = {
    'settle_demo_orders': {
        'task': 'api_trade.tasks.settle_demo_orders',
        'schedule': 5.0,
    },
    
    'periodic_price_updates': {
        'task': 'wsnotifications.tasks.periodic_price_updates',
        'schedule': crontab(minute="*/1")
    },
    'send_asset_specific_updates': {
        'task': 'wsnotifications.tasks.send_asset_specific_updates',
        'schedule': crontab(minute="*/2")
    },
    'send_email_verification_reminder': {
        'task': 'wsnotifications.tasks.send_email_verification_reminder',
        'schedule': crontab(minute="*/1")
    },
    'purge_expired_notifications': {
        'task': 'notifications.tasks.purge_expired_notifications',
        'schedule': crontab(hour=3, minute=15),
    },
}

NOTIFICATION_RETENTION_DAYS = int(os.getenv("NOTIFICATION_RETENTION_DAYS", "90"))
WEBHOOK_TIMEOUT_SECONDS = int(os.getenv("WEBHOOK_TIMEOUT_SECONDS", "10"))
STAGING_WEBHOOK_RECEIVER_SECRET = os.getenv("STAGING_WEBHOOK_RECEIVER_SECRET", "")
STAGING_WEBHOOK_RECEIVER_SECRET_FILE = os.getenv("STAGING_WEBHOOK_RECEIVER_SECRET_FILE", "")
if STAGING_WEBHOOK_RECEIVER_SECRET_FILE:
    try:
        STAGING_WEBHOOK_RECEIVER_SECRET = open(STAGING_WEBHOOK_RECEIVER_SECRET_FILE, "r", encoding="utf-8").read().strip()
    except OSError:
        STAGING_WEBHOOK_RECEIVER_SECRET = ""
STAGING_WEBHOOK_RECEIVER_ENABLED = API_ENV == "staging" and bool(STAGING_WEBHOOK_RECEIVER_SECRET)
DATA_ENCRYPTION_KEY_FILE = os.getenv("DATA_ENCRYPTION_KEY_FILE", "")
API_TOKEN_PEPPER_FILE = os.getenv("API_TOKEN_PEPPER_FILE", "")
WEBHOOK_MASTER_KEY_FILE = os.getenv("WEBHOOK_MASTER_KEY_FILE", "")
PASSWORD_RESET_SIGNING_KEY_FILE = os.getenv("PASSWORD_RESET_SIGNING_KEY_FILE", "")
DATA_ENCRYPTION_KEY = os.getenv("DATA_ENCRYPTION_KEY", "")
API_TOKEN_PEPPER = os.getenv("API_TOKEN_PEPPER", "")
WEBHOOK_MASTER_KEY = os.getenv("WEBHOOK_MASTER_KEY", "")

# CHANNELS
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/app/static"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

if os.getenv("RATE_LIMIT", "true").lower() in {"1", "true", "yes"}:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": os.getenv("ANON_RATE_LIMIT", "30/minute"),
        "user": os.getenv("USER_RATE_LIMIT", "300/minute"),
        "integration": "300/minute",
        "user_create": "30/minute",
        "import_upload": "5/hour",
        "import_action": "10/hour",
        "crm_inbound": "120/minute",
        "webhook_test": "5/minute",
        "webhook_retry": "10/hour",
        "guest_demo": "5/hour",
    }

# Simple-jwt
if DEBUG:
    # Token expiration time higher for dev environment
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1200),
        "REFRESH_TOKEN_LIFETIME": timedelta(hours=1200),
        "BLACKLIST_AFTER_ROTATION": True,
        "ROTATE_REFRESH_TOKENS": False,
    }

AUTH_USER_MODEL = "users.User"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

API_KEY_ALPACA = os.getenv("API_KEY_ALPACA")
SECRET_KEY_ALPACA = os.getenv("API_SECRET_ALPACA")
# Stripe Settings
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_ENDPOINT_SECRET = os.getenv("STRIPE_ENDPOINT_SECRET")

FRONTEND_URL = os.getenv("FRONTEND_URL")
SPECTACULAR_SETTINGS = {
    "TITLE": "Tradi Trading API",
    "DESCRIPTION": "Versioned API contract for the Tradi paper-trading platform.",
    "VERSION": "1.0.0",
    "COMPONENT_SPLIT_REQUEST": True,
    # Legacy hand-built JSON responses are represented by the documented
    # GenericApiResponse fallback. Suppress duplicate-name/type-guess chatter;
    # schema validation remains enabled in CI and deployment checks.
    "DISABLE_ERRORS_AND_WARNINGS": True,
    "PREPROCESSING_HOOKS": [
        "fx_utils.schema.add_legacy_serializer_fallback",
    ],
}
SILENCED_SYSTEM_CHECKS = ["drf_spectacular.W001"]

# Settings for import_export app
IMPORT_EXPORT_USE_TRANSACTIONS = True


# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # For developement
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

GEOIP_PATH = os.path.join(BASE_DIR, "GeoLite2-Country.mmdb")

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_SEND_FROM_NUMBER = os.getenv("TWILIO_SEND_FROM_NUMBER")


# Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "fx_utils.email.CustomAdminEmailHandler",
            "include_html": True,
        },
    },
    "formatters": {"json": {"()": "fx_utils.json_logging.JsonFormatter"}},
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

# Admins who get notified on errors
ADMINS = []
raw_admins = os.environ.get("ADMINS", None)
if raw_admins is not None:
    for admin in raw_admins.split("|"):
        name, email = admin.split(",")
        ADMINS.append([name, email])

# Because of django's hot reload, exclude promtheus metrics on debug mode
if not DEBUG:
    PROMETHEUS_METRICS_EXPORT_PORT_RANGE = range(7001, 7100)


NEWS_DATA_API_KEY: str = os.getenv("NEWS_DATA_API_KEY", "")
POLYGON_API_KEY: str = os.getenv("POLYGON_API_KEY", "")
TWELVE_DATA_API_KEY: str = os.getenv("TWELVE_DATA_API_KEY", "")
PROVIDER_CREDENTIAL_ROOT: str = os.getenv("PROVIDER_CREDENTIAL_ROOT", "/etc/codestra/providers")
COINGECKO_API_KEY: str = os.getenv("COINGECKO_API_KEY", "")
SCHEMA_API_KEY: str = os.getenv("SCHEMA_API_KEY", "")
TWELVE_DATA_REST_URL: str = os.getenv(
    "TWELVE_DATA_REST_URL", "https://api.twelvedata.com/time_series"
)
TWELVE_DATA_WEBSOCKET_URL: str = os.getenv(
    "TWELVE_DATA_WEBSOCKET_URL", "wss://ws.twelvedata.com/v1/quotes/price"
)
FIXER_API_KEY: str = os.getenv("FIXER_API_KEY", "")

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django's test client uses HTTP unless every call opts into TLS. Disable only
# the redirect middleware during test execution; deployed security stays intact.
if "test" in sys.argv:
    SECURE_SSL_REDIRECT = False
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    REST_FRAMEWORK.pop("DEFAULT_THROTTLE_CLASSES", None)
    REST_FRAMEWORK.pop("DEFAULT_THROTTLE_RATES", None)
