"""
Django settings for FX project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import json
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from celery.schedules import crontab


load_dotenv()

API_ENV = os.getenv("API_ENV")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.getenv("DEBUG"))

ALLOWED_HOSTS = json.loads(os.getenv("ALLOWED_HOSTS"))
CSRF_TRUSTED_ORIGINS = json.loads(os.getenv("CSRF_TRUSTED_ORIGINS"))

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

SHORT_UUID_LEN = os.getenv("SHORT_UUID_LEN", 9)

INSTALLED_APPS = [
    "daphne",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "django_prometheus",
    "drf_spectacular",
    "rest_framework",
    "rest_framework_simplejwt",
    "channels",
    "users",
    "api_trade",
    "wallet",
    "notifications",
    "ws",
    "news_app",
    "trade",
    "payments",
    "portfolio",
    "bank_account_app",
    "security",
    "coinmarketcharts",
    "django_celery_beat",
    "wsnotifications"
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "middleware.user_login_activity.UserLoginActivityMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    'middleware.user_preferred_language.UserPreferredLanguageMiddleware',
]

ROOT_URLCONF = "FX.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "FX.wsgi.application"

ASGI_APPLICATION = "FX.asgi.application"
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", '5432'),
    }
}

# REDIS
REDIS_CACHE_CUSTOM_TIMEOUT = os.getenv("REDIS_CACHE_CUSTOM_TIMEOUT", 30)
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_DATABASE = os.getenv("REDIS_DATABASE")
REDIS_POOL_MAX_CONNECTIONS = os.getenv("REDIS_POOL_MAX_CONNECTIONS")
REDIS_EXPIRE_KEY = os.getenv("REDIS_EXPIRE_KEY")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DATABASE}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# CELERY
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = {"application/json"}
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"


CELERY_BEAT_SCHEDULE = {
    'periodic_price_updates': {
        'task': 'wsnotifications.tasks.periodic_price_updates',
        'schedule': crontab(minute="*/1")
    },
    
    'asset_price_updates': {
        'task': 'wsnotifications.tasks.send_asset_specific_updates',
        'schedule': crontab(minute="*/1")
    }
}

# CHANNELS
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = '/app/static'



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

permission_type = "AllowAny" if API_ENV == "local" else "IsAuthenticated"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": (f"rest_framework.permissions.{permission_type}",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

if os.environ.get("RATE_LIMIT", False):
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ]
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "30/minute",
        "user": "60/minute",
    }

# Simple-jwt
if DEBUG:
    # Token expiration time higher for dev environment
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1200),
        "REFRESH_TOKEN_LIFETIME": timedelta(hours=1200),
        "BLACKLIST_AFTER_ROTATION": True,
        "ROTATE_REFRESH_TOKENS": False,
    }

AUTH_USER_MODEL = "users.User"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

API_KEY_ALPACA = os.getenv("API_KEY_ALPACA")
SECRET_KEY_ALPACA = os.getenv("API_SECRET_ALPACA")
CORS_ALLOW_ALL_ORIGINS = True

# Stripe Settings
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_ENDPOINT_SECRET = os.getenv("STRIPE_ENDPOINT_SECRET")

FRONTEND_URL = os.getenv("FRONTEND_URL")
SPECTACULAR_SETTINGS = {
    "TITLE": "FX Portal Backend",
    "DESCRIPTION": "API documentation for FX Portal Backend",
    "COMPONENT_SPLIT_REQUEST": True,
}

# Settings for import_export app
IMPORT_EXPORT_USE_TRANSACTIONS = True


# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # For developement
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

GEOIP_PATH = os.path.join(BASE_DIR, "GeoLite2-Country.mmdb")

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_SEND_FROM_NUMBER = os.getenv("TWILIO_SEND_FROM_NUMBER")


# Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": "/var/log/django.log",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "fx_utils.email.CustomAdminEmailHandler",
            "include_html": True,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

# Admins who get notified on errors
ADMINS = []
raw_admins = os.environ.get("ADMINS", None)
if raw_admins is not None:
    for admin in raw_admins.split("|"):
        name, email = admin.split(",")
        ADMINS.append([name, email])

# Because of django's hot reload, exclude promtheus metrics on debug mode
if not DEBUG:
    PROMETHEUS_METRICS_EXPORT_PORT_RANGE = range(7001, 7100)


NEWS_DATA_API_KEY: str = os.getenv("NEWS_DATA_API_KEY", "pub_5104020b15ee44b2ef4f00b0d7b0835337c8a")