# Generated by Django 5.0.2 on 2024-09-01 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='profit_loss',
        ),
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='portfolio.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_loss', models.FloatField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='portfolio.asset')),
            ],
        ),
    ]
