# Generated by Django 5.0.2 on 2024-09-12 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminipwhitelist",
            name="admin",
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
            },
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="is_successful",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="login_time",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="action_status",
            field=models.CharField(
                choices=[("", ""), ("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("LOGIN", "LOGIN"),
                    ("LOGOUT", "LOGOUT"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                    ("FORGOT_PASSWORD", "FORGOT_PASSWORD"),
                    ("CHANGE_PASSWORD", "CHANGE_PASSWORD"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="device_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="geolocation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CountryWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_whitelists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_whitelists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IPRestrictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("ALLOW_ALL", "Allow All"),
                            ("RESTRICT_BY_COUNTRY", "Restrict by Country"),
                            ("CUSTOM_IP_WHITELIST", "Custom IP Whitelist"),
                        ],
                        default="ALLOW_ALL",
                        max_length=50,
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country_whitelist",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ip_restrictions",
                        to="security.countrywhitelist",
                    ),
                ),
                (
                    "ip_whitelist",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ip_restrictions",
                        to="security.ipwhitelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("SPECIAL_CHARACTERS", "Special Characters"),
                            ("UPPERCASE_LOWERCASE", "Uppercase and Lowercase"),
                            (
                                "NUMBERS_AND_SPECIAL_CHARACTERS",
                                "Numbers and Special Characters",
                            ),
                            ("CUSTOM", "Custom"),
                        ],
                        default="SPECIAL_CHARACTERS",
                        max_length=50,
                    ),
                ),
                (
                    "custom_characters",
                    models.CharField(
                        blank=True,
                        help_text="Enter custom characters like @%^$ if 'Custom' is selected.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("min_length", models.PositiveIntegerField(default=8)),
                ("max_length", models.PositiveIntegerField(default=20)),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("STRONG", "STRONG"),
                            ("MODERATE", "MODERATE"),
                            ("WEAK", "WEAK"),
                        ],
                        default="MODERATE",
                        max_length=50,
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_policy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("AUTHENTICATOR_APP", "AUTHENTICATOR APP"),
                        ],
                        default="SMS",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="AdminIPWhitelist",
        ),
    ]
