# Generated by Django 5.0.2 on 2025-01-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_ipblacklist_iprestrictions_ip_blacklist_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="iprestrictions",
            name="user_ip_blacklist",
            field=models.ManyToManyField(blank=True, related_name="ip_restrictions", to="security.useripblacklist"),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="anonymous_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action_status",
            field=models.CharField(choices=[("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")], default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("LOGIN", "LOGIN"),
                    ("LOGOUT", "LOGOUT"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                    ("FORGOT_PASSWORD", "FORGOT_PASSWORD"),
                    ("CHANGE_PASSWORD", "CHANGE_PASSWORD"),
                    ("WHITELISTED_IP", "WHITELISTED_IP"),
                    ("WHITELISTED_COUNTRY", "WHITELISTED_COUNTRY"),
                    ("WHITELISTED_USER", "WHITELISTED_USER"),
                    ("BLACKLISTED_IP", "BLACKLISTED_IP"),
                    ("BLACKLISTED_COUNTRY", "BLACKLISTED_COUNTRY"),
                    ("BLACKLISTED_USER", "BLACKLISTED_USER"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CountryBlacklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_blacklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="iprestrictions",
            name="country_blacklist",
            field=models.ManyToManyField(blank=True, related_name="ip_restrictions", to="security.countryblacklist"),
        ),
    ]
