# Generated by Django 5.0.2 on 2025-01-18 15:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0004_iprestrictions_user_ip_blacklist_and_more"),
    ]
    operations = [
        migrations.CreateModel(
            name="AnomalyCheckSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_checked_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anomaly Check Status",
                "verbose_name_plural": "Anomaly Check Statuses",
            },
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("LOGIN", "LOGIN"),
                    ("LOGOUT", "LOGOUT"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                    ("FORGOT_PASSWORD", "FORGOT_PASSWORD"),
                    ("CHANGE_PASSWORD", "CHANGE_PASSWORD"),
                    ("WHITELISTED_IP", "WHITELISTED_IP"),
                    ("WHITELISTED_COUNTRY", "WHITELISTED_COUNTRY"),
                    ("WHITELISTED_USER", "WHITELISTED_USER"),
                    ("BLACKLISTED_IP", "BLACKLISTED_IP"),
                    ("INVALID_IP", "INVALID_IP"),
                    ("BLACKLISTED_COUNTRY", "BLACKLISTED_COUNTRY"),
                    ("BLACKLISTED_USER", "BLACKLISTED_USER"),
                    ("USER_ANOMALY_ALERT", "USER_ANOMALY_ALERT"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
