# Generated by Django 5.0.2 on 2025-01-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0005_anomalycheckschedule_alter_useractivity_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("LOGIN", "LOGIN"),
                    ("LOGOUT", "LOGOUT"),
                    ("PASSWORD_RESET", "PASSWORD_RESET"),
                    ("FORGOT_PASSWORD", "FORGOT_PASSWORD"),
                    ("CHANGE_PASSWORD", "CHANGE_PASSWORD"),
                    ("WHITELISTED_IP", "WHITELISTED_IP"),
                    ("WHITELISTED_COUNTRY", "WHITELISTED_COUNTRY"),
                    ("WHITELISTED_USER", "WHITELISTED_USER"),
                    ("BLACKLISTED_IP", "BLACKLISTED_IP"),
                    ("INVALID_IP", "INVALID_IP"),
                    ("BLACKLISTED_COUNTRY", "BLACKLISTED_COUNTRY"),
                    ("BLACKLISTED_USER", "BLACKLISTED_USER"),
                    ("USER_ANOMALY_ALERT", "USER_ANOMALY_ALERT"),
                    ("ADMIN_GLOBAL_SET_2FA", "ADMIN_GLOBAL_SET_2FA"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
